(()=>{
const API='https://my247-api.etoos247test.workers.dev';
const TK='my247Session';
let token=sessionStorage.getItem(TK)||'',me=null,currentView='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const entry=$('#entryView'),dash=$('#dashboardView'),work=$('#workspaceView'),body=$('#workspaceBody');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const campusName=c=>c==='suseong1'?'수성1관':c==='suseong2'?'수성2관':'전체';
const roleName=r=>r==='master'?'마스터':r==='teacher'?'교사':'학생';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),2600)}
function status(msg,kind=''){const e=$('#entryStatus');e.textContent=msg;e.className='entry-status '+kind}
async function api(path,opt={}){const h={...(opt.headers||{})};if(token)h.Authorization=`Bearer ${token}`;if(opt.body&&!(opt.body instanceof FormData)&&!h['Content-Type'])h['Content-Type']='application/json';const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(API+path,{...opt,headers:h,signal:c.signal,cache:'no-store'});const type=r.headers.get('content-type')||'';const d=type.includes('application/json')?await r.json():r;if(!r.ok)throw new Error(d?.message||`서버 오류 ${r.status}`);return d}finally{clearTimeout(timer)}}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden');$('#modalBody').innerHTML=''}
$('#modalClose').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});
function showEntry(){entry.classList.remove('hidden');dash.classList.add('hidden');work.classList.add('hidden');$('#accountBar').classList.add('hidden')}
function showDash(){entry.classList.add('hidden');dash.classList.remove('hidden');work.classList.add('hidden');$('#accountBar').classList.remove('hidden');$('#welcomeName').textContent=me.user.name;$('#welcomeMessage').textContent=me.user.role==='student'?'필요한 학원생활 메뉴를 선택하세요.':'오늘의 업무를 선택하세요.';$('#profileName').textContent=me.user.name;$('#profileMeta').textContent=`${me.user.loginId} · ${roleName(me.user.role)}`;$('#profileCampus').textContent=(me.campuses||[]).map(campusName).join(' · ')||'소속 미지정';$('#accountText').textContent=`${me.user.loginId} · ${me.user.name}`;$('#studentMenu').classList.toggle('hidden',me.user.role!=='student');$('#staffMenu').classList.toggle('hidden',me.user.role==='student');$('#accountAdminBtn').classList.toggle('hidden',me.user.role!=='master')}
async function restore(){if(!token){showEntry();return}try{me=await api('/api/me');showDash();if(me.user.mustChangePassword)toast('임시 비밀번호를 사용 중입니다. 비밀번호를 변경해 주세요.')}catch{sessionStorage.removeItem(TK);token='';showEntry()}}
async function health(){try{const h=await api('/health');status(h.ok?'시스템 연결 정상 · 학원 ID로 로그인하세요.':'서버 확인 필요','ok');const b=await fetch(API+'/api/bootstrap/status',{cache:'no-store'}).then(r=>r.json()).catch(()=>null);if(b?.needsMaster)$('#bootstrapOpen').classList.remove('hidden')}catch(e){status(e.name==='AbortError'?'서버 응답이 지연되고 있습니다.':`서버 연결 전 · ${e.message}`,'error')}}
$$('.login-form').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;status('계정을 확인하는 중입니다.');try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({loginId:f.loginId.value.trim(),password:f.password.value,mode:f.dataset.mode})});token=d.token;sessionStorage.setItem(TK,token);me={user:d.user,campuses:d.campuses};showDash();if(d.user.mustChangePassword)toast('최초 로그인입니다. 비밀번호를 변경해 주세요.')}catch(err){status(err.message,'error')}finally{b.disabled=false}}));
$('#logoutBtn').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}sessionStorage.removeItem(TK);token='';me=null;showEntry();health()};
$('#homeBtn').onclick=showDash;
$('#passwordBtn').onclick=()=>modal(`<h2>비밀번호 변경</h2><form id="pwForm" class="setup-grid"><label class="wide">현재 비밀번호<input name="current" type="password" required></label><label class="wide">새 비밀번호<input name="next" type="password" minlength="5" required placeholder="5자리 이상"></label><button class="primary wide" type="submit">변경</button></form>`);
document.addEventListener('submit',async e=>{if(e.target.id!=='pwForm')return;e.preventDefault();try{const d=await api('/api/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:e.target.current.value,newPassword:e.target.next.value})});token=d.token;sessionStorage.setItem(TK,token);me.user.mustChangePassword=false;closeModal();toast('비밀번호를 변경했습니다.')}catch(err){toast(err.message)}});
$('#bootstrapOpen').onclick=()=>modal(`<h2>최초 마스터 설정</h2><p>새 시스템에서 한 번만 실행합니다. Cloudflare에 등록한 최초 설정 키가 필요합니다.</p><form id="bootstrapForm" class="setup-grid"><label class="wide">최초 설정 키<input name="bootstrapKey" type="password" required></label><label>마스터 ID<input name="loginId" value="ADMIN001" required></label><label>이름<input name="name" required></label><label class="wide">비밀번호<input name="password" type="password" minlength="5" required></label><button class="primary wide" type="submit">마스터 생성</button></form>`);
document.addEventListener('submit',async e=>{if(e.target.id!=='bootstrapForm')return;e.preventDefault();const f=e.target;try{const r=await fetch(API+'/api/bootstrap/master',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bootstrapKey:f.bootstrapKey.value,loginId:f.loginId.value,name:f.name.value,password:f.password.value})}),d=await r.json();if(!r.ok)throw new Error(d.message);closeModal();$('#bootstrapOpen').classList.add('hidden');toast('최초 마스터가 생성되었습니다. 교사용으로 로그인하세요.')}catch(err){toast(err.message)}});
$$('[data-view]').forEach(b=>b.onclick=()=>openView(b.dataset.view));
async function openView(v){currentView=v;dash.classList.add('hidden');work.classList.remove('hidden');body.innerHTML='<div class="empty">자료를 불러오는 중입니다.</div>';const title={notices:'공지사항',schedules:'시험일정',questions:'질의응답',admission:'입시탐색기'}[v];$('#workspaceTitle').textContent=title;$('#workspaceKicker').textContent=me.user.role==='student'?'STUDENT LIFE':'TEACHER WORK';try{if(v==='notices')await notices();if(v==='schedules')await schedules();if(v==='questions')await questions();if(v==='admission')admission()}catch(e){body.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function noticeCard(n,staff){return`<article class="item"><h3>${esc(n.title)}</h3><div class="meta">${n.pinned?'상단고정 · ':''}${campusName(n.campus)} · ${esc(n.author_name||'학원')} · ${esc((n.created_at||'').slice(0,10))}</div><div class="body">${esc(n.body)}</div>${staff?`<div class="actions"><button data-edit-notice='${esc(JSON.stringify(n))}'>수정</button><button class="danger" data-delete-notice="${n.id}">삭제</button></div>`:''}</article>`}
async function notices(){const d=await api('/api/notices'),staff=me.user.role!=='student';body.innerHTML=`<div class="content-grid"><div class="list">${d.notices.length?d.notices.map(n=>noticeCard(n,staff)).join(''):'<div class="empty">등록된 공지가 없습니다.</div>'}</div>${staff?noticeEditor():''}</div>`;bindNotice()}
function noticeEditor(n={}){return`<form id="noticeForm" class="editor"><h2>${n.id?'공지 수정':'공지 등록'}</h2><input type="hidden" name="id" value="${n.id||''}"><label>제목<input name="title" value="${esc(n.title||'')}" required></label><label>내용<textarea name="body" required>${esc(n.body||'')}</textarea></label><label>대상관<select name="campus"><option value="">전체</option><option value="suseong1">수성1관</option><option value="suseong2">수성2관</option></select></label><label>대상<select name="audience"><option value="all">전체</option><option value="student">학생</option><option value="staff">교사</option></select></label><div class="checks"><label><input name="pinned" type="checkbox"> 상단고정</label><label><input name="visible" type="checkbox" checked> 공개</label></div><button class="primary" type="submit">저장</button></form>`}
function bindNotice(){const f=$('#noticeForm');if(f)f.onsubmit=async e=>{e.preventDefault();const x=e.target,b={title:x.title.value,body:x.body.value,campus:x.campus.value||null,audience:x.audience.value,pinned:x.pinned.checked,visible:x.visible.checked};try{await api(x.id.value?`/api/notices/${x.id.value}`:'/api/notices',{method:x.id.value?'PATCH':'POST',body:JSON.stringify(b)});toast('공지를 저장했습니다.');notices()}catch(err){toast(err.message)}};$$('[data-edit-notice]').forEach(b=>b.onclick=()=>{const n=JSON.parse(b.dataset.editNotice);$('.editor').outerHTML=noticeEditor(n);const f=$('#noticeForm');f.campus.value=n.campus||'';f.audience.value=n.audience||'all';f.pinned.checked=!!n.pinned;f.visible.checked=n.visible!==0;bindNotice()});$$('[data-delete-notice]').forEach(b=>b.onclick=async()=>{if(!confirm('이 공지를 삭제할까요?'))return;await api(`/api/notices/${b.dataset.deleteNotice}/delete`,{method:'POST'});notices()})}
function scheduleCard(n,staff){return`<article class="item"><h3>${esc(n.period_label)} · ${esc(n.title)}</h3><div class="meta">${esc(n.exam_date)} · ${campusName(n.campus)}</div><div class="body">${esc(n.description||'')}</div>${staff?`<div class="actions"><button data-edit-schedule='${esc(JSON.stringify(n))}'>수정</button><button class="danger" data-delete-schedule="${n.id}">삭제</button></div>`:''}</article>`}
async function schedules(){const d=await api('/api/schedules'),staff=me.user.role!=='student';body.innerHTML=`<div class="content-grid"><div class="list">${d.schedules.length?d.schedules.map(n=>scheduleCard(n,staff)).join(''):'<div class="empty">등록된 시험일정이 없습니다.</div>'}</div>${staff?scheduleEditor():''}</div>`;bindSchedule()}
function scheduleEditor(n={}){return`<form id="scheduleForm" class="editor"><h2>${n.id?'일정 수정':'시험일정 등록'}</h2><input type="hidden" name="id" value="${n.id||''}"><label>시험일<input name="examDate" type="date" value="${n.exam_date||''}" required></label><label>회차<input name="periodLabel" value="${esc(n.period_label||'')}" placeholder="예: 3월 1차" required></label><label>시험명<input name="title" value="${esc(n.title||'')}" required></label><label>안내<textarea name="description">${esc(n.description||'')}</textarea></label><label>대상관<select name="campus"><option value="">전체</option><option value="suseong1">수성1관</option><option value="suseong2">수성2관</option></select></label><div class="checks"><label><input name="visible" type="checkbox" checked> 공개</label></div><button class="primary" type="submit">저장</button></form>`}
function bindSchedule(){const f=$('#scheduleForm');if(f)f.onsubmit=async e=>{e.preventDefault();const x=e.target,b={examDate:x.examDate.value,periodLabel:x.periodLabel.value,title:x.title.value,description:x.description.value,campus:x.campus.value||null,visible:x.visible.checked};try{await api(x.id.value?`/api/schedules/${x.id.value}`:'/api/schedules',{method:x.id.value?'PATCH':'POST',body:JSON.stringify(b)});toast('시험일정을 저장했습니다.');schedules()}catch(err){toast(err.message)}};$$('[data-edit-schedule]').forEach(b=>b.onclick=()=>{const n=JSON.parse(b.dataset.editSchedule);$('.editor').outerHTML=scheduleEditor(n);const f=$('#scheduleForm');f.campus.value=n.campus||'';f.visible.checked=n.visible!==0;bindSchedule()});$$('[data-delete-schedule]').forEach(b=>b.onclick=async()=>{if(!confirm('이 시험일정을 삭제할까요?'))return;await api(`/api/schedules/${b.dataset.deleteSchedule}/delete`,{method:'POST'});schedules()})}
function qCard(q){return`<article class="q-card"><button data-qid="${q.id}"><span class="q-status">${q.status==='open'?'답변대기':q.status==='answered'?'답변완료':'종료'}</span><h3>${esc(q.subject)} · ${esc(q.title)}</h3><div class="meta">${me.user.role==='student'?'':`${esc(q.student_name)} · ${esc(q.student_no||q.student_login)} · `}${esc((q.updated_at||'').slice(0,16).replace('T',' '))}</div></button></article>`}
async function questions(){const d=await api('/api/questions');body.innerHTML=`<div class="content-grid"><div><div class="q-list">${d.questions.length?d.questions.map(qCard).join(''):'<div class="empty">질문이 없습니다.</div>'}</div></div>${me.user.role==='student'?questionEditor():`<aside class="editor"><h2>답변 업무</h2><p>왼쪽 질문을 선택하면 대화와 답변 입력창이 열립니다.</p></aside>`}</div>`;$$('[data-qid]').forEach(b=>b.onclick=()=>questionDetail(b.dataset.qid));const f=$('#questionForm');if(f)f.onsubmit=createQuestion}
function questionEditor(){return`<form id="questionForm" class="editor"><h2>새 질문</h2><label>과목<select name="subject"><option>국어</option><option>수학</option><option>영어</option><option>사탐</option><option>과탐</option><option>입시</option></select></label><label>제목<input name="title" required></label><label>질문내용<textarea name="body" required></textarea></label><label>사진<input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><p class="meta">사진 최대 3장 · 장당 1MB 이하</p><button class="primary" type="submit">질문 등록</button></form>`}
async function createQuestion(e){e.preventDefault();const f=e.target,fd=new FormData();fd.set('subject',f.subject.value);fd.set('title',f.title.value);fd.set('body',f.body.value);[...f.images.files].slice(0,3).forEach(x=>fd.append('images',x));try{await api('/api/questions',{method:'POST',body:fd});toast('질문을 등록했습니다.');questions()}catch(err){toast(err.message)}}
async function questionDetail(id){const d=await api(`/api/questions/${id}`),q=d.question;body.innerHTML=`<div class="content-grid"><div><article class="item"><span class="q-status">${q.status}</span><h3>${esc(q.subject)} · ${esc(q.title)}</h3><div class="meta">${esc(q.student_name)} · ${esc(q.student_login)}</div></article><div class="list">${d.messages.map(m=>`<article class="message ${m.author_role!=='student'?'staff':''}"><strong>${esc(m.author_name)} · ${roleName(m.author_role)}</strong><p>${esc(m.body)}</p>${m.attachments?.length?`<div class="files">${m.attachments.map(a=>`<button class="secondary" data-file="${esc(a.url)}">${esc(a.name)}</button>`).join('')}</div>`:''}</article>`).join('')}</div></div><form id="replyForm" class="editor"><h2>${me.user.role==='student'?'재질문':'답변 작성'}</h2><textarea name="body" required placeholder="내용을 입력하세요."></textarea><label>사진<input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><button class="primary" type="submit">등록</button><button id="closeQ" class="secondary" type="button">질문 종료</button></form></div>`;$('#replyForm').onsubmit=async e=>{e.preventDefault();const f=e.target,fd=new FormData();fd.set('body',f.body.value);[...f.images.files].slice(0,3).forEach(x=>fd.append('images',x));try{await api(`/api/questions/${id}/messages`,{method:'POST',body:fd});questionDetail(id)}catch(err){toast(err.message)}};$('#closeQ').onclick=async()=>{await api(`/api/questions/${id}/close`,{method:'POST'});questions()};$$('[data-file]').forEach(b=>b.onclick=()=>openProtectedFile(b.dataset.file))}
async function openProtectedFile(path){try{const r=await fetch(API+path,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('파일을 열 수 없습니다.');const url=URL.createObjectURL(await r.blob());window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){toast(e.message)}}
function admission(){body.innerHTML=`<div class="admission-box"><article class="admission-card"><small>ADMISSION EXPLORER</small><h2>입시탐색기</h2><p>대학·학과·전형 탐색과 상담 준비에 사용하는 입시 도구입니다. 현재 연결된 입시 도구를 새 창에서 엽니다.</p><a href="https://ipsywan.com/" target="_blank" rel="noopener">입시탐색 시작 ↗</a></article><article class="admission-card"><small>INTERNAL GUIDE</small><h2>입학·상담 자료</h2><p>학원 내부의 입학·상담 운영 기준과 참고자료를 확인합니다.</p><a href="./admission/" target="_blank">상담 자료 보기 ↗</a></article></div>`}
$('#accountAdminBtn').onclick=accountAdmin;
async function accountAdmin(){try{const d=await api('/api/users');modal(`<h2>마스터 ID 관리</h2><p>학생·교사 ID는 마스터가 직접 발급합니다. 초기 비밀번호는 첫 로그인 후 변경하도록 안내합니다.</p><form id="userCreateForm" class="setup-grid"><label>구분<select name="role"><option value="student">학생</option><option value="teacher">교사</option></select></label><label>ID<input name="loginId" placeholder="M001 / T001" required></label><label>이름<input name="name" required></label><label>임시 비밀번호<input name="temporaryPassword" minlength="5" required></label><label>학생 소속관<select name="campus"><option value="suseong1">수성1관</option><option value="suseong2">수성2관</option></select></label><label>학생번호<input name="studentNo" placeholder="M001 / S001"></label><label class="wide">교사 담당관 <span><input name="c1" type="checkbox" value="suseong1"> 수성1관　<input name="c2" type="checkbox" value="suseong2"> 수성2관</span></label><button class="primary wide" type="submit">ID 발급</button></form><hr><div id="userRows">${userRows(d.users)}</div>`);$('#userCreateForm').onsubmit=createUser;bindUsers()}catch(e){toast(e.message)}}
function userRows(users){return users.map(u=>`<div class="user-row"><strong>${esc(u.loginId)}<small>${esc(u.name)}</small></strong><span>${roleName(u.role)}</span><span>${campusName(u.campus)}</span><span>${u.active?'사용':'중지'}</span><div class="user-actions"><button class="secondary" data-reset="${u.loginId}">PW 초기화</button>${u.role!=='master'?`<button class="secondary" data-active="${u.loginId}" data-on="${u.active?'1':'0'}">${u.active?'중지':'재개'}</button>`:''}</div></div>`).join('')||'<div class="empty">계정이 없습니다.</div>'}
async function createUser(e){e.preventDefault();const f=e.target,role=f.role.value,b={role,loginId:f.loginId.value,name:f.name.value,temporaryPassword:f.temporaryPassword.value,campus:f.campus.value,studentNo:f.studentNo.value,campuses:[f.c1.checked?'suseong1':'',f.c2.checked?'suseong2':''].filter(Boolean)};try{await api('/api/users',{method:'POST',body:JSON.stringify(b)});toast('ID를 발급했습니다.');accountAdmin()}catch(err){toast(err.message)}}
function bindUsers(){$$('[data-reset]').forEach(b=>b.onclick=async()=>{const pw=prompt(`${b.dataset.reset} 새 임시 비밀번호(5자 이상)`);if(!pw)return;try{await api(`/api/users/${encodeURIComponent(b.dataset.reset)}/reset-password`,{method:'POST',body:JSON.stringify({temporaryPassword:pw})});toast('비밀번호를 초기화했습니다.')}catch(e){toast(e.message)}});$$('[data-active]').forEach(b=>b.onclick=async()=>{try{await api(`/api/users/${encodeURIComponent(b.dataset.active)}/active`,{method:'PATCH',body:JSON.stringify({active:b.dataset.on!=='1'})});accountAdmin()}catch(e){toast(e.message)}})}
health();restore();
})();