(()=>{
const API='https://my247-api.etoos247test.workers.dev';
const TK='my247Session';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const typeName=t=>t==='master'?'마스터':t==='submaster'?'준마스터':t==='teacher'?'교사':'학생';
const campusName=c=>c==='suseong1'?'수성1관':c==='suseong2'?'수성2관':c||'-';
let session=null,catalog=[],users=[];
const DEFAULTS={
  teacher:['notice.read','notice.create','notice.edit','schedule.read','schedule.create','schedule.edit','question.read','question.reply','question.close','admission.read'],
  submaster:['account.read','account.create.student','account.password.reset','account.status.manage','notice.read','notice.create','notice.edit','notice.delete','schedule.read','schedule.create','schedule.edit','schedule.delete','question.read','question.reply','question.close','admission.read','counseling.read','counseling.write','intake.read','intake.manage','notification.read','planner.read','planner.stats.read']
};
function token(){return sessionStorage.getItem(TK)||''}
async function api(path,opt={}){const h={...(opt.headers||{}),Authorization:`Bearer ${token()}`};if(opt.body&&!h['Content-Type'])h['Content-Type']='application/json';const r=await fetch(API+path,{...opt,headers:h,cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`서버 오류 ${r.status}`);return d}
function toast(msg){const t=$('#toast');if(!t)return alert(msg);t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.add('hidden'),2800)}
function openModal(html){const m=$('#modal'),b=$('#modalBody');if(!m||!b)return;b.innerHTML=html;m.classList.remove('hidden');}
function can(key){return session?.user?.accountType==='master'||session?.permissions?.includes(key)}
function injectStyle(){if($('#rbacStyle'))return;const s=document.createElement('style');s.id='rbacStyle';s.textContent=`
.modal-box.rbac-wide{width:min(1180px,96vw)}
.rbac-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.rbac-head p{margin:7px 0 0;color:#6b7a72;line-height:1.65}.rbac-badge{display:inline-flex;padding:6px 9px;border-radius:999px;background:#eef5f1;color:#2f6c50;font-size:11px;font-weight:900}
.rbac-create{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:16px;border:1px solid #dfe7e2;border-radius:14px;background:#fafcfb}.rbac-create label{font-size:12px;font-weight:850}.rbac-create input,.rbac-create select{width:100%;margin-top:5px;padding:10px 11px;border:1px solid #ccd9d2;border-radius:9px;background:white}.rbac-wide-row{grid-column:1/-1}.rbac-campus{display:flex;gap:18px;align-items:center;min-height:42px}.rbac-campus label{font-weight:700}.rbac-perms{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:10px}.rbac-perm-group{border:1px solid #dfe7e2;border-radius:12px;padding:12px;background:#fff}.rbac-perm-group h4{margin:0 0 9px;font-size:13px}.rbac-perm-group label{display:flex;gap:7px;align-items:flex-start;margin:7px 0;font-weight:650;line-height:1.35}.rbac-perm-group input{width:auto;margin:2px 0 0}.rbac-preset{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0}.rbac-preset button{border:1px solid #d3dfd8;background:#fff;border-radius:8px;padding:7px 10px;font-size:11px;font-weight:850}.rbac-users{margin-top:20px;display:grid;gap:8px}.rbac-row{display:grid;grid-template-columns:1.15fr .7fr .9fr .55fr 1.5fr;gap:10px;align-items:center;padding:12px;border:1px solid #e1e8e4;border-radius:11px;background:#fff}.rbac-row strong{display:flex;flex-direction:column;gap:3px}.rbac-row small{color:#75827b}.rbac-actions{display:flex;gap:6px;justify-content:flex-end;flex-wrap:wrap}.rbac-actions button{border:1px solid #d3ddd7;background:#fff;border-radius:8px;padding:7px 9px;font-size:11px;font-weight:850}.rbac-actions .danger{color:#a33;background:#fff4f4!important}.rbac-note{margin:12px 0;padding:10px 12px;border-left:3px solid #6d907d;background:#f4f8f5;color:#5f6e66;font-size:12px;line-height:1.6}
@media(max-width:900px){.rbac-create{grid-template-columns:1fr 1fr}.rbac-perms{grid-template-columns:1fr 1fr}.rbac-row{grid-template-columns:1fr 1fr}.rbac-actions{grid-column:1/-1;justify-content:flex-start}}
@media(max-width:600px){.rbac-create,.rbac-perms{grid-template-columns:1fr}.rbac-row{grid-template-columns:1fr}.rbac-wide-row{grid-column:auto}}
`;document.head.appendChild(s)}
function setModalWide(on){$('#modal .modal-box')?.classList.toggle('rbac-wide',!!on)}
function permissionHtml(selected=[],editable=true){const set=new Set(selected);return `<div class="rbac-perms">${catalog.map(g=>`<section class="rbac-perm-group"><h4>${esc(g.group)}</h4>${g.items.map(i=>{const disabled=!editable||(!can(i.key)&&session?.user?.accountType!=='master');return `<label><input type="checkbox" name="perm" value="${esc(i.key)}" ${set.has(i.key)?'checked':''} ${disabled?'disabled':''}><span>${esc(i.label)}</span></label>`}).join('')}</section>`).join('')}</div>`}
function selectedPerms(form){return [...form.querySelectorAll('input[name="perm"]:checked')].map(x=>x.value)}
function applyPreset(form,type){const wanted=new Set(type==='teacher'?DEFAULTS.teacher:type==='submaster'?DEFAULTS.submaster:[]);form.querySelectorAll('input[name="perm"]').forEach(x=>{if(!x.disabled)x.checked=wanted.has(x.value)})}
function campusControls(prefix=''){return `<div class="rbac-campus"><label><input name="${prefix}c1" type="checkbox" value="suseong1"> 수성1관</label><label><input name="${prefix}c2" type="checkbox" value="suseong2"> 수성2관</label></div>`}
function syncCreateForm(form){const t=form.accountType.value,student=t==='student';form.querySelector('[data-student-fields]').hidden=!student;form.querySelector('[data-staff-fields]').hidden=student;form.querySelector('[data-permission-fields]').hidden=student}
async function loadAdmin(){const d=await api('/api/rbac/users');catalog=d.permissionCatalog||[];users=d.users||[];renderAdmin()}
function renderAdmin(){injectStyle();setModalWide(true);const createOptions=[['student','학생','account.create.student'],['teacher','교사','account.create.teacher'],['submaster','준마스터','account.create.submaster']].filter(x=>can(x[2]));openModal(`<div class="rbac-head"><div><span class="rbac-badge">MASTER ACCESS CONTROL</span><h2>계정 · 소속관 · 세부 권한 관리</h2><p>학생·교사·준마스터 ID를 발급하고 수성1관·수성2관 범위와 기능별 권한을 개별 부여합니다.</p></div></div>${createOptions.length?`<form id="rbacCreateForm" class="rbac-create"><label>계정 구분<select name="accountType">${createOptions.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label><label>ID<input name="loginId" placeholder="S001 / T001 / SM001" required></label><label>이름<input name="name" required></label><label>임시 비밀번호<input name="temporaryPassword" minlength="5" required></label><div class="rbac-wide-row" data-student-fields><label>학생 소속관<select name="campus"><option value="suseong1">수성1관</option><option value="suseong2">수성2관</option></select></label> <label>학생번호 <input name="studentNo" placeholder="선택 입력"></label></div><div class="rbac-wide-row" data-staff-fields hidden><b>담당관</b>${campusControls()}</div><div class="rbac-wide-row" data-permission-fields hidden><div class="rbac-preset"><button type="button" data-preset="teacher">교사 기본권한</button><button type="button" data-preset="submaster">준마스터 기본권한</button><button type="button" data-all="1">전체 선택</button><button type="button" data-all="0">전체 해제</button></div>${permissionHtml([])}</div><button class="primary rbac-wide-row" type="submit">ID 발급</button></form>`:'<div class="rbac-note">현재 계정에는 새 ID 발급 권한이 없습니다.</div>'}<div class="rbac-users">${rowsHtml()}</div>`);bindAdmin()}
function rowsHtml(){return users.map(u=>`<div class="rbac-row"><strong>${esc(u.loginId)}<small>${esc(u.name)}</small></strong><span>${typeName(u.accountType)}</span><span>${u.campuses?.length?u.campuses.map(campusName).join(' · '):campusName(u.campus)}</span><span>${u.active?'사용':'중지'}</span><div class="rbac-actions">${u.accountType!=='master'&&can('account.permission.manage')?`<button data-access="${esc(u.loginId)}">권한·담당관</button>`:''}${u.accountType!=='master'&&can('account.password.reset')?`<button data-reset="${esc(u.loginId)}">PW 초기화</button>`:''}${u.accountType!=='master'&&can('account.status.manage')?`<button class="${u.active?'danger':''}" data-active="${esc(u.loginId)}" data-on="${u.active?'1':'0'}">${u.active?'중지':'재개'}</button>`:''}</div></div>`).join('')||'<div class="empty">표시할 계정이 없습니다.</div>'}
function bindAdmin(){const f=$('#rbacCreateForm');if(f){syncCreateForm(f);f.accountType.onchange=()=>{syncCreateForm(f);applyPreset(f,f.accountType.value)};f.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(f,b.dataset.preset));f.querySelectorAll('[data-all]').forEach(b=>b.onclick=()=>f.querySelectorAll('input[name="perm"]:not(:disabled)').forEach(x=>x.checked=b.dataset.all==='1'));f.onsubmit=async e=>{e.preventDefault();const t=f.accountType.value,payload={accountType:t,loginId:f.loginId.value.trim(),name:f.name.value.trim(),temporaryPassword:f.temporaryPassword.value,permissions:selectedPerms(f)};if(t==='student'){payload.campus=f.campus.value;payload.studentNo=f.studentNo.value.trim()}else payload.campuses=[f.c1.checked?'suseong1':'',f.c2.checked?'suseong2':''].filter(Boolean);try{await api('/api/rbac/users',{method:'POST',body:JSON.stringify(payload)});toast('ID를 발급했습니다.');await loadAdmin()}catch(err){toast(err.message)}}}
$$('[data-access]').forEach(b=>b.onclick=()=>editAccess(b.dataset.access));$$('[data-reset]').forEach(b=>b.onclick=async()=>{const pw=prompt(`${b.dataset.reset} 새 임시 비밀번호(5자 이상)`);if(!pw)return;try{await api(`/api/rbac/users/${encodeURIComponent(b.dataset.reset)}/reset-password`,{method:'POST',body:JSON.stringify({temporaryPassword:pw})});toast('비밀번호를 초기화했습니다.')}catch(e){toast(e.message)}});$$('[data-active]').forEach(b=>b.onclick=async()=>{try{await api(`/api/rbac/users/${encodeURIComponent(b.dataset.active)}/active`,{method:'PATCH',body:JSON.stringify({active:b.dataset.on!=='1'})});await loadAdmin()}catch(e){toast(e.message)}})}
function editAccess(id){const u=users.find(x=>x.loginId===id);if(!u)return;setModalWide(true);const student=u.accountType==='student';openModal(`<div class="rbac-head"><div><span class="rbac-badge">${esc(u.loginId)}</span><h2>${esc(u.name)} 권한 설정</h2><p>계정 종류, 담당관과 기능별 권한을 조정합니다.</p></div><button class="secondary" id="rbacBack" type="button">← 목록</button></div><form id="rbacAccessForm" class="rbac-create"><label>계정 구분<select name="accountType" ${student?'disabled':''}><option value="teacher" ${u.accountType==='teacher'?'selected':''}>교사</option><option value="submaster" ${u.accountType==='submaster'?'selected':''}>준마스터</option>${student?'<option value="student" selected>학생</option>':''}</select></label>${student?`<label>학생 소속관<select name="campus"><option value="suseong1" ${u.campus==='suseong1'?'selected':''}>수성1관</option><option value="suseong2" ${u.campus==='suseong2'?'selected':''}>수성2관</option></select></label>`:`<div class="rbac-wide-row"><b>담당관</b>${campusControls('e')}</div><div class="rbac-wide-row"><div class="rbac-preset"><button type="button" data-preset="teacher">교사 기본권한</button><button type="button" data-preset="submaster">준마스터 기본권한</button><button type="button" data-all="1">전체 선택</button><button type="button" data-all="0">전체 해제</button></div>${permissionHtml(u.permissions||[])}</div>`}<button class="primary rbac-wide-row" type="submit">변경 저장</button></form>`);$('#rbacBack').onclick=renderAdmin;const f=$('#rbacAccessForm');if(!student){f.ec1.checked=u.campuses?.includes('suseong1');f.ec2.checked=u.campuses?.includes('suseong2');f.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(f,b.dataset.preset));f.querySelectorAll('[data-all]').forEach(b=>b.onclick=()=>f.querySelectorAll('input[name="perm"]:not(:disabled)').forEach(x=>x.checked=b.dataset.all==='1'))}f.onsubmit=async e=>{e.preventDefault();const payload={accountType:student?'student':f.accountType.value,permissions:student?[]:selectedPerms(f)};if(student)payload.campus=f.campus.value;else payload.campuses=[f.ec1.checked?'suseong1':'',f.ec2.checked?'suseong2':''].filter(Boolean);try{await api(`/api/rbac/users/${encodeURIComponent(id)}/access`,{method:'PATCH',body:JSON.stringify(payload)});toast('권한을 저장했습니다.');await loadAdmin()}catch(err){toast(err.message)}}}
function enforceWorkspace(){if(!session||session.user.role==='student'||session.user.accountType==='master')return;const title=$('#workspaceTitle')?.textContent?.trim();if(title==='공지사항'){$$('.editor').forEach(x=>{if(!can('notice.create'))x.style.display='none'});$$('[data-edit-notice]').forEach(x=>x.style.display=can('notice.edit')?'':'none');$$('[data-delete-notice]').forEach(x=>x.style.display=can('notice.delete')?'':'none')}if(title==='시험일정'){$$('.editor').forEach(x=>{if(!can('schedule.create'))x.style.display='none'});$$('[data-edit-schedule]').forEach(x=>x.style.display=can('schedule.edit')?'':'none');$$('[data-delete-schedule]').forEach(x=>x.style.display=can('schedule.delete')?'':'none')}if(title==='질의응답'){$('#replyForm')&&($('#replyForm').style.display=can('question.reply')?'':'none');$('#closeQ')&&($('#closeQ').style.display=can('question.close')?'':'none')}}
function applyMenu(){if(!session)return;const admin=$('#accountAdminBtn');if(admin){const show=can('account.read');admin.classList.toggle('hidden',!show);if(show)admin.onclick=()=>loadAdmin().catch(e=>toast(e.message))}if(session.user.accountType==='submaster'){const meta=$('#profileMeta');if(meta)meta.textContent=`${session.user.loginId} · 준마스터 계정`}
const rules=[['[data-view="notices"]','notice.read'],['[data-view="schedules"]','schedule.read'],['[data-view="questions"]','question.read'],['[data-view="admission"]','admission.read'],['a[href="./apply/admin/"]','intake.read'],['a[href="./notifications/"]','notification.read']];if(session.user.role!=='student'&&session.user.accountType!=='master')for(const [sel,key] of rules)$('#staffMenu')?.querySelectorAll(sel).forEach(x=>x.style.display=can(key)?'':'none');enforceWorkspace()}
async function refresh(){if(!token())return;try{session=await api('/api/me');applyMenu()}catch{}}
function boot(){injectStyle();refresh();const account=$('#accountBar'),work=$('#workspaceBody');if(account)new MutationObserver(()=>setTimeout(refresh,0)).observe(account,{attributes:true,attributeFilter:['class']});if(work)new MutationObserver(()=>setTimeout(enforceWorkspace,0)).observe(work,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
