const E=new TextEncoder();
const now=()=>new Date().toISOString();
const txt=(v,n=2000)=>String(v??'').trim().slice(0,n);
const CAMPUS=new Set(['suseong1','suseong2','undecided']);
const STATUS=new Set(['new','contacted','reserved','counseled','registered','closed']);
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const fail=(s,m)=>{throw new HttpError(s,m)};
function cors(req,env){const o=req.headers.get('origin'),a=env.ALLOWED_ORIGIN||'https://etoos247test.github.io';return{'Access-Control-Allow-Origin':o===a?o:a,'Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, PATCH, OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin'}}
function json(req,env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(req,env),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(v){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',E.encode(v))))}
async function auth(req,env){const m=/^Bearer\s+(sid_[A-Za-z0-9_-]+)$/.exec(req.headers.get('authorization')||'');if(!m)fail(401,'로그인이 필요합니다.');const h=await sha(m[1]);const u=await env.DB.prepare('SELECT u.*,s.expires_at FROM core_sessions s JOIN core_users u ON u.id=s.user_id WHERE s.token_hash=?').bind(h).first();if(!u||u.active!==1)fail(401,'유효하지 않은 로그인입니다.');if(u.expires_at<=now())fail(401,'로그인이 만료되었습니다.');if(!['teacher','master'].includes(u.role))fail(403,'교사용 기능입니다.');return u}
async function campuses(env,u){if(u.role==='master')return['suseong1','suseong2'];const r=await env.DB.prepare('SELECT campus FROM core_user_campuses WHERE user_id=? ORDER BY campus').bind(u.id).all();return r.results.map(x=>x.campus)}
async function canSee(env,u,campus){if(u.role==='master'||campus==='undecided')return true;return(await campuses(env,u)).includes(campus)}
async function audit(env,u,a,k,detail=null){await env.DB.prepare('INSERT INTO core_audit_logs(id,actor_id,action,target_type,target_key,detail_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),u?.id||null,a,'application',k,detail?JSON.stringify(detail):null,now()).run()}
const digits=v=>txt(v,30).replace(/[^0-9]/g,'').slice(0,11);
function receipt(){const d=now().slice(0,10).replaceAll('-','');return`A${d}-${crypto.randomUUID().replaceAll('-','').slice(0,6).toUpperCase()}`}
async function createApplication(req,env){const origin=req.headers.get('origin'),allowed=env.ALLOWED_ORIGIN||'https://etoos247test.github.io';if(origin&&origin!==allowed)fail(403,'허용되지 않은 접수 요청입니다.');const b=await req.json().catch(()=>({}));if(txt(b.website,100))return{ok:true,receiptNo:'RECEIVED'};const studentName=txt(b.studentName,40),phone=digits(b.phone),campus=txt(b.campus,20),program=txt(b.program,60),applicantType=b.applicantType==='guardian'?'guardian':'student';if(studentName.length<2)fail(400,'학생 이름을 입력하세요.');if(phone.length<9)fail(400,'연락처를 확인하세요.');if(!CAMPUS.has(campus))fail(400,'상담 희망 관을 선택하세요.');if(program.length<2)fail(400,'상담 희망 과정을 선택하세요.');if(b.privacyAgree!==true)fail(400,'개인정보 수집·이용 동의가 필요합니다.');const id=crypto.randomUUID(),receiptNo=receipt(),n=now(),subjects=Array.isArray(b.subjects)?[...new Set(b.subjects.map(x=>txt(x,20)).filter(Boolean))].slice(0,10):[];await env.DB.prepare('INSERT INTO core_applications(id,receipt_no,source,applicant_type,student_name,school,grade,phone,guardian_phone,campus,program,subjects_json,preferred_date,inquiry,status,privacy_agreed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,\'new\',?,?,?)').bind(id,receiptNo,txt(b.source,80)||'general-qr',applicantType,studentName,txt(b.school,80),txt(b.grade,30),phone,digits(b.guardianPhone),campus,program,JSON.stringify(subjects),txt(b.preferredDate,20),txt(b.inquiry,3000),n,n,n).run();await audit(env,null,'application.create',id,{receiptNo,campus,source:txt(b.source,80)||'general-qr'});return{ok:true,receiptNo}}
async function getApplication(env,id){const a=await env.DB.prepare('SELECT * FROM core_applications WHERE id=?').bind(id).first();if(!a)fail(404,'접수 건을 찾을 수 없습니다.');return a}
async function listApplications(env,u){const cs=await campuses(env,u);let q=`SELECT a.*,au.login_id assigned_login,au.name assigned_name,su.login_id student_login,su.student_no FROM core_applications a LEFT JOIN core_users au ON au.id=a.assigned_to LEFT JOIN core_users su ON su.id=a.student_user_id`;
let r;if(u.role==='master')r=await env.DB.prepare(q+` ORDER BY CASE a.status WHEN 'new' THEN 0 WHEN 'contacted' THEN 1 WHEN 'reserved' THEN 2 WHEN 'counseled' THEN 3 WHEN 'registered' THEN 4 ELSE 5 END,a.created_at DESC LIMIT 500`).all();else{const where=cs.length?` WHERE a.campus='undecided' OR a.campus IN (${cs.map(()=>'?').join(',')})`:` WHERE a.campus='undecided'`;r=await env.DB.prepare(q+where+` ORDER BY CASE a.status WHEN 'new' THEN 0 WHEN 'contacted' THEN 1 WHEN 'reserved' THEN 2 WHEN 'counseled' THEN 3 WHEN 'registered' THEN 4 ELSE 5 END,a.created_at DESC LIMIT 500`).bind(...cs).all()}return{applications:r.results}}
async function listStaff(env,u){let r;if(u.role==='master')r=await env.DB.prepare("SELECT DISTINCT u.login_id,u.name,u.role FROM core_users u WHERE u.active=1 AND u.role IN ('master','teacher') ORDER BY CASE u.role WHEN 'master' THEN 0 ELSE 1 END,u.name").all();else{const cs=await campuses(env,u);if(!cs.length)return{staff:[{loginId:u.login_id,name:u.name,role:u.role}]};const marks=cs.map(()=>'?').join(',');r=await env.DB.prepare(`SELECT DISTINCT u.login_id,u.name,u.role FROM core_users u LEFT JOIN core_user_campuses c ON c.user_id=u.id WHERE u.active=1 AND (u.role='master' OR (u.role='teacher' AND c.campus IN (${marks}))) ORDER BY CASE u.role WHEN 'master' THEN 0 ELSE 1 END,u.name`).bind(...cs).all()}return{staff:r.results.map(x=>({loginId:x.login_id,name:x.name,role:x.role}))}}
async function updateApplication(req,env,u,id){const a=await getApplication(env,id);if(!(await canSee(env,u,a.campus)))fail(403,'해당 접수 건을 관리할 권한이 없습니다.');const b=await req.json().catch(()=>({}));let campus=b.campus===undefined?a.campus:txt(b.campus,20);if(!CAMPUS.has(campus))fail(400,'상담 관을 확인하세요.');if(!(await canSee(env,u,campus)))fail(403,'해당 상담 관으로 배정할 권한이 없습니다.');let assigned=a.assigned_to;if(Object.prototype.hasOwnProperty.call(b,'assignedLoginId')){const key=txt(b.assignedLoginId,64).toUpperCase();if(!key)assigned=null;else{const t=await env.DB.prepare("SELECT * FROM core_users WHERE login_id=? AND active=1 AND role IN ('master','teacher')").bind(key).first();if(!t)fail(400,'담당 교사를 찾을 수 없습니다.');if(campus!=='undecided'&&t.role!=='master'&&!(await campuses(env,t)).includes(campus))fail(400,'선택한 교사는 해당 관 담당이 아닙니다.');assigned=t.id}}
const status=STATUS.has(b.status)?b.status:a.status,n=now();await env.DB.prepare('UPDATE core_applications SET campus=?,status=?,assigned_to=?,appointment_at=?,counsel_note=?,updated_at=? WHERE id=?').bind(campus,status,assigned,txt(b.appointmentAt,40),txt(b.counselNote,5000),n,id).run();await audit(env,u,'application.update',id,{status,campus,assignedLoginId:txt(b.assignedLoginId,64)});return{ok:true}}
async function linkStudent(req,env,u,id){if(u.role!=='master')fail(403,'마스터만 재원생 ID를 연결할 수 있습니다.');const a=await getApplication(env,id),b=await req.json().catch(()=>({})),key=txt(b.studentLoginId,64).toUpperCase();if(!key)fail(400,'학생 ID를 입력하세요.');const s=await env.DB.prepare("SELECT * FROM core_users WHERE role='student' AND active=1 AND (login_id=? OR student_no=?)").bind(key,key).first();if(!s)fail(404,'재원생 ID를 찾을 수 없습니다.');await env.DB.prepare("UPDATE core_applications SET student_user_id=?,status='registered',updated_at=? WHERE id=?").bind(s.id,now(),id).run();await audit(env,u,'application.link-student',id,{studentLoginId:s.login_id});return{ok:true,studentLoginId:s.login_id}}
async function route(req,env){const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req,env)});if(req.method==='GET'&&p==='/health')return json(req,env,{ok:true,service:'my247-intake-api',storage:'D1'});if(req.method==='POST'&&p==='/api/applications')return json(req,env,await createApplication(req,env),201);const user=await auth(req,env);if(req.method==='GET'&&p==='/api/applications')return json(req,env,await listApplications(env,user));if(req.method==='GET'&&p==='/api/staff')return json(req,env,await listStaff(env,user));let m;if(req.method==='PATCH'&&(m=/^\/api\/applications\/([^/]+)$/.exec(p)))return json(req,env,await updateApplication(req,env,user,m[1]));if(req.method==='POST'&&(m=/^\/api\/applications\/([^/]+)\/link-student$/.exec(p)))return json(req,env,await linkStudent(req,env,user,m[1]));fail(404,'요청한 기능을 찾을 수 없습니다.')}
export default{async fetch(req,env){try{return await route(req,env)}catch(e){return json(req,env,{ok:false,message:e.message||'서버 오류'},e.status||500)}}};
