const E=new TextEncoder(),ITER=100000,TTL=12*60*60*1000,LOCK=10*60*1000;
const CAMPUS=new Set(['suseong1','suseong2']),ROLES=new Set(['master','teacher','student']);
const now=()=>new Date().toISOString(),txt=(v,n=2000)=>String(v??'').trim().slice(0,n),lid=v=>txt(v,64).toUpperCase();
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const fail=(s,m)=>{throw new HttpError(s,m)};
function cors(req,env){const o=req.headers.get('origin'),a=env.ALLOWED_ORIGIN||'https://etoos247test.github.io';return{'Access-Control-Allow-Origin':o===a?o:a,'Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, PATCH, OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin'}}
function json(req,env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(req,env),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
function unhex(s){const b=new Uint8Array(s.length/2);for(let i=0;i<b.length;i++)b[i]=parseInt(s.slice(i*2,i*2+2),16);return b}
async function sha(v){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',E.encode(v))))}
async function derive(p,salt,it=ITER){const k=await crypto.subtle.importKey('raw',E.encode(String(p)),'PBKDF2',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:Math.min(it,100000)},k,256))}
async function hashPassword(p){p=String(p||'');if(p.length<5)fail(400,'비밀번호는 5자 이상이어야 합니다.');const s=new Uint8Array(16);crypto.getRandomValues(s);return`pbkdf2-sha256$${ITER}$${hex(s)}$${hex(await derive(p,s))}`}
async function verifyPassword(p,h){const a=String(h||'').split('$');if(a.length!==4)return false;const x=await derive(p,unhex(a[2]),Number(a[1])),y=unhex(a[3]);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);let s='';for(const x of b)s+=String.fromCharCode(x);return'sid_'+btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
async function schemaReady(env){return!!(await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='core_users'").first())}
async function audit(env,u,a,t,k='',detail=null){await env.DB.prepare('INSERT INTO core_audit_logs(id,actor_id,action,target_type,target_key,detail_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),u||null,a,t,k,detail?JSON.stringify(detail):null,now()).run()}
async function byLogin(env,id){return env.DB.prepare('SELECT * FROM core_users WHERE login_id=?').bind(lid(id)).first()}
const pub=u=>({loginId:u.login_id,name:u.name,role:u.role,campus:u.campus||'',studentNo:u.student_no||'',active:u.active===1,mustChangePassword:u.must_change_password===1});
async function campuses(env,u){if(u.role==='master')return['suseong1','suseong2'];if(u.role==='student')return u.campus?[u.campus]:[];const r=await env.DB.prepare('SELECT campus FROM core_user_campuses WHERE user_id=? ORDER BY campus').bind(u.id).all();return r.results.map(x=>x.campus)}
async function newSession(env,uid){const t=token(),h=await sha(t),n=now(),e=new Date(Date.now()+TTL).toISOString();await env.DB.prepare('INSERT INTO core_sessions(token_hash,user_id,expires_at,created_at,last_seen_at) VALUES(?,?,?,?,?)').bind(h,uid,e,n,n).run();return t}
async function auth(req,env){const m=/^Bearer\s+(sid_[A-Za-z0-9_-]+)$/.exec(req.headers.get('authorization')||'');if(!m)fail(401,'로그인이 필요합니다.');const h=await sha(m[1]);const u=await env.DB.prepare('SELECT u.*,s.expires_at FROM core_sessions s JOIN core_users u ON u.id=s.user_id WHERE s.token_hash=?').bind(h).first();if(!u||u.active!==1)fail(401,'유효하지 않은 로그인입니다.');if(u.expires_at<=now()){await env.DB.prepare('DELETE FROM core_sessions WHERE token_hash=?').bind(h).run();fail(401,'로그인이 만료되었습니다.')}await env.DB.prepare('UPDATE core_sessions SET last_seen_at=? WHERE token_hash=?').bind(now(),h).run();return{user:u,hash:h}}
const requireRole=(u,r)=>{if(!r.includes(u.role))fail(403,'이 기능을 사용할 권한이 없습니다.')};
async function checkCampus(env,u,c){if(!CAMPUS.has(c))fail(400,'소속관을 확인하세요.');if(!(await campuses(env,u)).includes(c))fail(403,'해당 소속관 권한이 없습니다.')}
async function studentByKey(env,k){k=lid(k);const u=await env.DB.prepare("SELECT * FROM core_users WHERE role='student' AND (login_id=? OR student_no=?)").bind(k,k).first();if(!u)fail(404,'학생을 찾을 수 없습니다.');return u}

async function bootstrapStatus(env){if(!(await schemaReady(env)))return{schemaReady:false,needsMaster:true};const r=await env.DB.prepare("SELECT COUNT(*) n FROM core_users WHERE role='master'").first();return{schemaReady:true,needsMaster:Number(r?.n||0)===0}}
async function bootstrap(req,env){if(!(await schemaReady(env)))fail(503,'D1 스키마를 먼저 적용해야 합니다.');const s=await bootstrapStatus(env);if(!s.needsMaster)fail(409,'최초 마스터 설정이 이미 완료되었습니다.');const b=await req.json().catch(()=>({}));if(!env.MASTER_BOOTSTRAP_KEY||b.bootstrapKey!==env.MASTER_BOOTSTRAP_KEY)fail(403,'최초 설정 키가 맞지 않습니다.');const id=lid(b.loginId),name=txt(b.name,40);if(!/^[A-Z0-9._-]{3,64}$/.test(id)||name.length<2)fail(400,'마스터 정보를 확인하세요.');const uid=crypto.randomUUID(),t=now();await env.DB.prepare("INSERT INTO core_users(id,login_id,password_hash,name,role,active,must_change_password,created_at,updated_at) VALUES(?,?,?,?,'master',1,0,?,?)").bind(uid,id,await hashPassword(b.password),name,t,t).run();await audit(env,uid,'bootstrap.master','user',id);return{ok:true,loginId:id,name}}
async function login(req,env){if(!(await schemaReady(env)))fail(503,'D1 스키마가 준비되지 않았습니다.');const b=await req.json().catch(()=>({})),id=lid(b.loginId),mode=txt(b.mode,10),u=await byLogin(env,id);if(!u)fail(401,'ID 또는 비밀번호가 맞지 않습니다.');if(mode==='student'&&u.role!=='student')fail(403,'학생용 로그인에서 사용할 수 없는 계정입니다.');if(mode==='staff'&&!['teacher','master'].includes(u.role))fail(403,'교사용 로그인에서 사용할 수 없는 계정입니다.');if(u.active!==1)fail(403,'이용이 중지된 계정입니다.');if(u.locked_until&&u.locked_until>now())fail(429,'로그인 실패가 반복되어 10분간 잠겨 있습니다.');if(!(await verifyPassword(b.password,u.password_hash))){const c=Number(u.failed_count||0)+1,l=c>=5?new Date(Date.now()+LOCK).toISOString():null;await env.DB.prepare('UPDATE core_users SET failed_count=?,locked_until=?,updated_at=? WHERE id=?').bind(c>=5?0:c,l,now(),u.id).run();fail(401,'ID 또는 비밀번호가 맞지 않습니다.')}const n=now();await env.DB.batch([env.DB.prepare('UPDATE core_users SET failed_count=0,locked_until=NULL,last_login_at=?,updated_at=? WHERE id=?').bind(n,n,u.id),env.DB.prepare('DELETE FROM core_sessions WHERE expires_at<=?').bind(n)]);return{token:await newSession(env,u.id),user:pub(u),campuses:await campuses(env,u)}}
async function me(env,c){return{user:pub(c.user),campuses:await campuses(env,c.user)}}
async function logout(env,c){await env.DB.prepare('DELETE FROM core_sessions WHERE token_hash=?').bind(c.hash).run();return{ok:true}}
async function changePassword(req,env,c){const b=await req.json().catch(()=>({}));if(!(await verifyPassword(b.currentPassword,c.user.password_hash)))fail(401,'현재 비밀번호가 맞지 않습니다.');const h=await hashPassword(b.newPassword),n=now();await env.DB.batch([env.DB.prepare('UPDATE core_users SET password_hash=?,must_change_password=0,failed_count=0,locked_until=NULL,updated_at=? WHERE id=?').bind(h,n,c.user.id),env.DB.prepare('DELETE FROM core_sessions WHERE user_id=?').bind(c.user.id)]);return{ok:true,token:await newSession(env,c.user.id)}}

async function listUsers(env,c){requireRole(c.user,['master']);const r=await env.DB.prepare("SELECT login_id,name,role,campus,student_no,active,must_change_password,last_login_at FROM core_users ORDER BY CASE role WHEN 'master' THEN 0 WHEN 'teacher' THEN 1 ELSE 2 END,name").all();return{users:r.results.map(x=>({loginId:x.login_id,name:x.name,role:x.role,campus:x.campus||'',studentNo:x.student_no||'',active:x.active===1,mustChangePassword:x.must_change_password===1,lastLoginAt:x.last_login_at||''}))}}
async function createUser(req,env,c){requireRole(c.user,['master']);const b=await req.json().catch(()=>({})),id=lid(b.loginId),role=txt(b.role,10),name=txt(b.name,40);if(!/^[A-Z0-9._-]{3,64}$/.test(id)||!ROLES.has(role)||role==='master'&&b.allowMaster!==true||name.length<2)fail(400,'계정 정보를 확인하세요.');if(await byLogin(env,id))fail(409,'이미 사용 중인 ID입니다.');let campus=null,studentNo=null;if(role==='student'){campus=txt(b.campus,20);if(!CAMPUS.has(campus))fail(400,'학생 소속관을 선택하세요.');studentNo=lid(b.studentNo||id)}const uid=crypto.randomUUID(),n=now(),stm=[env.DB.prepare('INSERT INTO core_users(id,login_id,password_hash,name,role,campus,student_no,active,must_change_password,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,1,?,?)').bind(uid,id,await hashPassword(b.temporaryPassword),name,role,campus,studentNo,n,n)];if(role==='teacher'){const cs=Array.isArray(b.campuses)?b.campuses.filter(x=>CAMPUS.has(x)):[];if(!cs.length)fail(400,'교사 소속관을 하나 이상 선택하세요.');for(const x of cs)stm.push(env.DB.prepare('INSERT INTO core_user_campuses(user_id,campus,created_at) VALUES(?,?,?)').bind(uid,x,n))}await env.DB.batch(stm);await audit(env,c.user.id,'user.create','user',id,{role,campus});return{ok:true,user:{loginId:id,name,role,campus,studentNo}}}
async function resetPassword(req,env,c,id){requireRole(c.user,['master']);const u=await byLogin(env,id);if(!u)fail(404,'계정을 찾을 수 없습니다.');const b=await req.json().catch(()=>({}));await env.DB.batch([env.DB.prepare('UPDATE core_users SET password_hash=?,must_change_password=1,failed_count=0,locked_until=NULL,updated_at=? WHERE id=?').bind(await hashPassword(b.temporaryPassword),now(),u.id),env.DB.prepare('DELETE FROM core_sessions WHERE user_id=?').bind(u.id)]);return{ok:true}}
async function setActive(req,env,c,id){requireRole(c.user,['master']);const u=await byLogin(env,id);if(!u)fail(404,'계정을 찾을 수 없습니다.');if(u.id===c.user.id)fail(400,'현재 마스터 계정은 중지할 수 없습니다.');const b=await req.json().catch(()=>({})),a=b.active?1:0;await env.DB.batch([env.DB.prepare('UPDATE core_users SET active=?,updated_at=? WHERE id=?').bind(a,now(),u.id),env.DB.prepare('DELETE FROM core_sessions WHERE user_id=?').bind(u.id)]);return{ok:true}}

async function listNotices(env,c){const u=c.user,staff=u.role!=='student',cs=await campuses(env,u);const q=staff?`SELECT n.*,u.login_id author_login,u.name author_name FROM core_notices n JOIN core_users u ON u.id=n.author_id WHERE n.campus IS NULL OR n.campus IN (${cs.map(()=>'?').join(',')||"''"}) ORDER BY n.pinned DESC,n.created_at DESC LIMIT 200`:`SELECT n.*,u.name author_name FROM core_notices n JOIN core_users u ON u.id=n.author_id WHERE n.visible=1 AND (n.audience='all' OR n.audience='student') AND (n.campus IS NULL OR n.campus=?) ORDER BY n.pinned DESC,n.created_at DESC LIMIT 100`;const r=staff?await env.DB.prepare(q).bind(...cs).all():await env.DB.prepare(q).bind(u.campus).all();return{notices:r.results}}
async function saveNotice(req,env,c,id=null){requireRole(c.user,['teacher','master']);const b=await req.json().catch(()=>({})),title=txt(b.title,140),body=txt(b.body,5000),campus=b.campus?txt(b.campus,20):null;if(title.length<2||body.length<1)fail(400,'공지 제목과 내용을 입력하세요.');if(campus){await checkCampus(env,c.user,campus)}const n=now();if(id){await env.DB.prepare('UPDATE core_notices SET title=?,body=?,campus=?,audience=?,pinned=?,visible=?,updated_at=? WHERE id=?').bind(title,body,campus,['all','student','staff'].includes(b.audience)?b.audience:'all',b.pinned?1:0,b.visible===false?0:1,n,id).run()}else{id=crypto.randomUUID();await env.DB.prepare('INSERT INTO core_notices(id,title,body,campus,audience,pinned,visible,author_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,title,body,campus,['all','student','staff'].includes(b.audience)?b.audience:'all',b.pinned?1:0,b.visible===false?0:1,c.user.id,n,n).run()}await audit(env,c.user.id,'notice.save','notice',id);return{ok:true,id}}
async function deleteNotice(env,c,id){requireRole(c.user,['teacher','master']);await env.DB.prepare('DELETE FROM core_notices WHERE id=?').bind(id).run();await audit(env,c.user.id,'notice.delete','notice',id);return{ok:true}}

async function listSchedules(env,c){const u=c.user,staff=u.role!=='student',cs=await campuses(env,u);const q=staff?`SELECT * FROM core_exam_schedules WHERE campus IS NULL OR campus IN (${cs.map(()=>'?').join(',')||"''"}) ORDER BY exam_date,created_at`:`SELECT * FROM core_exam_schedules WHERE visible=1 AND (campus IS NULL OR campus=?) ORDER BY exam_date,created_at`;const r=staff?await env.DB.prepare(q).bind(...cs).all():await env.DB.prepare(q).bind(u.campus).all();return{schedules:r.results}}
async function saveSchedule(req,env,c,id=null){requireRole(c.user,['teacher','master']);const b=await req.json().catch(()=>({})),date=txt(b.examDate,10),label=txt(b.periodLabel,60),title=txt(b.title,140),desc=txt(b.description,3000),campus=b.campus?txt(b.campus,20):null;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!label||!title)fail(400,'시험일·회차·시험명을 확인하세요.');if(campus)await checkCampus(env,c.user,campus);const n=now();if(id)await env.DB.prepare('UPDATE core_exam_schedules SET exam_date=?,period_label=?,title=?,description=?,campus=?,visible=?,updated_at=? WHERE id=?').bind(date,label,title,desc,campus,b.visible===false?0:1,n,id).run();else{id=crypto.randomUUID();await env.DB.prepare('INSERT INTO core_exam_schedules(id,exam_date,period_label,title,description,campus,visible,author_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,date,label,title,desc,campus,b.visible===false?0:1,c.user.id,n,n).run()}await audit(env,c.user.id,'schedule.save','schedule',id);return{ok:true,id}}
async function deleteSchedule(env,c,id){requireRole(c.user,['teacher','master']);await env.DB.prepare('DELETE FROM core_exam_schedules WHERE id=?').bind(id).run();return{ok:true}}

async function listQuestions(env,c){const u=c.user;if(u.role==='student'){const r=await env.DB.prepare('SELECT q.*,u.name student_name,u.login_id student_login FROM core_questions q JOIN core_users u ON u.id=q.student_id WHERE q.student_id=? ORDER BY q.updated_at DESC').bind(u.id).all();return{questions:r.results}}const cs=await campuses(env,u),q=`SELECT q.*,u.name student_name,u.login_id student_login,u.student_no FROM core_questions q JOIN core_users u ON u.id=q.student_id WHERE q.campus IN (${cs.map(()=>'?').join(',')||"''"}) ORDER BY CASE q.status WHEN 'open' THEN 0 WHEN 'answered' THEN 1 ELSE 2 END,q.updated_at DESC`;return{questions:(await env.DB.prepare(q).bind(...cs).all()).results}}
async function createQuestion(req,env,c){requireRole(c.user,['student']);const form=await req.formData(),title=txt(form.get('title'),140),subject=txt(form.get('subject'),30),body=txt(form.get('body'),5000);if(!title||!subject||!body)fail(400,'과목·제목·질문 내용을 입력하세요.');const qid=crypto.randomUUID(),mid=crypto.randomUUID(),n=now();await env.DB.batch([env.DB.prepare("INSERT INTO core_questions(id,student_id,campus,subject,title,status,created_at,updated_at) VALUES(?,?,?,?,?,'open',?,?)").bind(qid,c.user.id,c.user.campus,subject,title,n,n),env.DB.prepare('INSERT INTO core_messages(id,question_id,author_id,body,created_at) VALUES(?,?,?,?,?)').bind(mid,qid,c.user.id,body,n)]);await uploadImages(form,env,c.user.id,'message',mid,qid);return{ok:true,id:qid}}
async function questionDetail(env,c,id){const q=await env.DB.prepare('SELECT q.*,u.name student_name,u.login_id student_login FROM core_questions q JOIN core_users u ON u.id=q.student_id WHERE q.id=?').bind(id).first();if(!q)fail(404,'질문을 찾을 수 없습니다.');if(c.user.role==='student'&&q.student_id!==c.user.id)fail(403,'접근할 수 없습니다.');if(c.user.role!=='student')await checkCampus(env,c.user,q.campus);const m=await env.DB.prepare('SELECT m.id,m.body,m.created_at,u.login_id author_login,u.name author_name,u.role author_role FROM core_messages m JOIN core_users u ON u.id=m.author_id WHERE m.question_id=? ORDER BY m.created_at').bind(id).all();const ids=m.results.map(x=>x.id);let attachments=[];if(ids.length){const qs=ids.map(()=>'?').join(',');attachments=(await env.DB.prepare(`SELECT entity_id,object_key,original_name,content_type FROM core_attachments WHERE entity_type='message' AND entity_id IN (${qs})`).bind(...ids).all()).results}return{question:q,messages:m.results.map(x=>({...x,attachments:attachments.filter(a=>a.entity_id===x.id).map(a=>({name:a.original_name,url:`/api/files/${encodeURIComponent(a.object_key)}`}))}))}}
async function addMessage(req,env,c,qid){const q=await env.DB.prepare('SELECT * FROM core_questions WHERE id=?').bind(qid).first();if(!q)fail(404,'질문을 찾을 수 없습니다.');if(c.user.role==='student'&&q.student_id!==c.user.id)fail(403,'접근할 수 없습니다.');if(c.user.role!=='student')await checkCampus(env,c.user,q.campus);const form=await req.formData(),body=txt(form.get('body'),5000);if(!body)fail(400,'내용을 입력하세요.');const mid=crypto.randomUUID(),n=now(),status=c.user.role==='student'?'open':'answered';await env.DB.batch([env.DB.prepare('INSERT INTO core_messages(id,question_id,author_id,body,created_at) VALUES(?,?,?,?,?)').bind(mid,qid,c.user.id,body,n),env.DB.prepare('UPDATE core_questions SET status=?,updated_at=? WHERE id=?').bind(status,n,qid)]);await uploadImages(form,env,c.user.id,'message',mid,qid);return{ok:true}}
async function closeQuestion(env,c,id){const q=await env.DB.prepare('SELECT * FROM core_questions WHERE id=?').bind(id).first();if(!q)fail(404,'질문을 찾을 수 없습니다.');if(c.user.role==='student'&&q.student_id!==c.user.id)fail(403,'접근할 수 없습니다.');if(c.user.role!=='student')await checkCampus(env,c.user,q.campus);await env.DB.prepare("UPDATE core_questions SET status='closed',updated_at=? WHERE id=?").bind(now(),id).run();return{ok:true}}
async function uploadImages(form,env,userId,type,entityId,qid){const files=form.getAll('images').filter(x=>x&&typeof x==='object'&&'arrayBuffer'in x).slice(0,3);for(const f of files){if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>1048576)fail(400,'사진은 JPG·PNG·WebP, 장당 1MB 이하만 가능합니다.');const aid=crypto.randomUUID(),ext=f.type==='image/png'?'png':f.type==='image/webp'?'webp':'jpg',key=`my247/${qid}/${aid}.${ext}`,bytes=await f.arrayBuffer();await env.ATTACHMENTS.put(key,bytes,{httpMetadata:{contentType:f.type}});await env.DB.prepare('INSERT INTO core_attachments(id,entity_type,entity_id,object_key,original_name,content_type,size_bytes,uploader_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(aid,type,entityId,key,txt(f.name,180),f.type,f.size,userId,now()).run()}}
async function fileResponse(env,c,key){const row=await env.DB.prepare('SELECT * FROM core_attachments WHERE object_key=?').bind(key).first();if(!row)fail(404,'파일을 찾을 수 없습니다.');if(row.entity_type==='message'){const q=await env.DB.prepare('SELECT q.* FROM core_messages m JOIN core_questions q ON q.id=m.question_id WHERE m.id=?').bind(row.entity_id).first();if(c.user.role==='student'&&q?.student_id!==c.user.id)fail(403,'접근할 수 없습니다.');if(c.user.role!=='student'&&q)await checkCampus(env,c.user,q.campus)}const obj=await env.ATTACHMENTS.get(key);if(!obj)fail(404,'파일을 찾을 수 없습니다.');return new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata?.contentType||row.content_type,'Cache-Control':'private, max-age=300'}})}

async function route(req,env){const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req,env)});if(req.method==='GET'&&p==='/health')return json(req,env,{ok:true,service:'my247-api',auth:'company-id',storage:'D1+R2'});if(req.method==='GET'&&p==='/api/bootstrap/status')return json(req,env,await bootstrapStatus(env));if(req.method==='POST'&&p==='/api/bootstrap/master')return json(req,env,await bootstrap(req,env),201);if(req.method==='POST'&&p==='/api/auth/login')return json(req,env,await login(req,env));const c=await auth(req,env);if(req.method==='GET'&&p==='/api/me')return json(req,env,await me(env,c));if(req.method==='POST'&&p==='/api/auth/logout')return json(req,env,await logout(env,c));if(req.method==='POST'&&p==='/api/auth/change-password')return json(req,env,await changePassword(req,env,c));if(req.method==='GET'&&p==='/api/users')return json(req,env,await listUsers(env,c));if(req.method==='POST'&&p==='/api/users')return json(req,env,await createUser(req,env,c),201);let m;if(req.method==='POST'&&(m=/^\/api\/users\/([^/]+)\/reset-password$/.exec(p)))return json(req,env,await resetPassword(req,env,c,decodeURIComponent(m[1])));if(req.method==='PATCH'&&(m=/^\/api\/users\/([^/]+)\/active$/.exec(p)))return json(req,env,await setActive(req,env,c,decodeURIComponent(m[1])));if(req.method==='GET'&&p==='/api/notices')return json(req,env,await listNotices(env,c));if(req.method==='POST'&&p==='/api/notices')return json(req,env,await saveNotice(req,env,c),201);if(req.method==='PATCH'&&(m=/^\/api\/notices\/([^/]+)$/.exec(p)))return json(req,env,await saveNotice(req,env,c,m[1]));if(req.method==='POST'&&(m=/^\/api\/notices\/([^/]+)\/delete$/.exec(p)))return json(req,env,await deleteNotice(env,c,m[1]));if(req.method==='GET'&&p==='/api/schedules')return json(req,env,await listSchedules(env,c));if(req.method==='POST'&&p==='/api/schedules')return json(req,env,await saveSchedule(req,env,c),201);if(req.method==='PATCH'&&(m=/^\/api\/schedules\/([^/]+)$/.exec(p)))return json(req,env,await saveSchedule(req,env,c,m[1]));if(req.method==='POST'&&(m=/^\/api\/schedules\/([^/]+)\/delete$/.exec(p)))return json(req,env,await deleteSchedule(env,c,m[1]));if(req.method==='GET'&&p==='/api/questions')return json(req,env,await listQuestions(env,c));if(req.method==='POST'&&p==='/api/questions')return json(req,env,await createQuestion(req,env,c),201);if(req.method==='GET'&&(m=/^\/api\/questions\/([^/]+)$/.exec(p)))return json(req,env,await questionDetail(env,c,m[1]));if(req.method==='POST'&&(m=/^\/api\/questions\/([^/]+)\/messages$/.exec(p)))return json(req,env,await addMessage(req,env,c,m[1]),201);if(req.method==='POST'&&(m=/^\/api\/questions\/([^/]+)\/close$/.exec(p)))return json(req,env,await closeQuestion(env,c,m[1]));if(req.method==='GET'&&(m=/^\/api\/files\/(.+)$/.exec(p)))return fileResponse(env,c,decodeURIComponent(m[1]));fail(404,'요청한 기능을 찾을 수 없습니다.')}
export default{async fetch(req,env){try{return await route(req,env)}catch(e){return json(req,env,{ok:false,message:e.message||'서버 오류'},e.status||500)}}};
