const E=new TextEncoder(),ITER=100000,TTL=12*60*60*1000,LOCK=10*60*1000;
const now=()=>new Date().toISOString();
const txt=(v,n=2000)=>String(v??'').trim().slice(0,n);
const lid=v=>txt(v,64).toUpperCase();
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const fail=(s,m)=>{throw new HttpError(s,m)};
function cors(req,env){const o=req.headers.get('origin'),a=env.ALLOWED_ORIGIN||'https://etoos247test.github.io';return{'Access-Control-Allow-Origin':o===a?o:a,'Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin'}}
function json(req,env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(req,env),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
function unhex(s){const b=new Uint8Array(s.length/2);for(let i=0;i<b.length;i++)b[i]=parseInt(s.slice(i*2,i*2+2),16);return b}
async function sha(v){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',E.encode(v))))}
async function derive(p,salt,it=ITER){const k=await crypto.subtle.importKey('raw',E.encode(String(p)),'PBKDF2',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:Math.min(it,100000)},k,256))}
async function verifyPassword(p,h){const a=String(h||'').split('$');if(a.length!==4)return false;const x=await derive(p,unhex(a[2]),Number(a[1])),y=unhex(a[3]);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function sessionToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);let s='';for(const x of b)s+=String.fromCharCode(x);return'sid_'+btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
async function newSession(env,uid){const t=sessionToken(),h=await sha(t),n=now(),e=new Date(Date.now()+TTL).toISOString();await env.DB.prepare('INSERT INTO core_sessions(token_hash,user_id,expires_at,created_at,last_seen_at) VALUES(?,?,?,?,?)').bind(h,uid,e,n,n).run();return t}
async function audit(env,u,a,t,k='',detail=null){await env.DB.prepare('INSERT INTO core_audit_logs(id,actor_id,action,target_type,target_key,detail_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),u||null,a,t,k,detail?JSON.stringify(detail):null,now()).run()}
async function byLogin(env,id){return env.DB.prepare('SELECT * FROM core_users WHERE login_id=?').bind(lid(id)).first()}
async function sessionAuth(req,env){const m=/^Bearer\s+(sid_[A-Za-z0-9_-]+)$/.exec(req.headers.get('authorization')||'');if(!m)fail(401,'로그인이 필요합니다.');const h=await sha(m[1]);const u=await env.DB.prepare('SELECT u.*,s.expires_at FROM core_sessions s JOIN core_users u ON u.id=s.user_id WHERE s.token_hash=?').bind(h).first();if(!u||u.active!==1)fail(401,'유효하지 않은 로그인입니다.');if(u.expires_at<=now()){await env.DB.prepare('DELETE FROM core_sessions WHERE token_hash=?').bind(h).run();fail(401,'로그인이 만료되었습니다.')}await env.DB.prepare('UPDATE core_sessions SET last_seen_at=? WHERE token_hash=?').bind(now(),h).run();return{user:u,hash:h}}
function requireMaster(c){if(c.user.role!=='master')fail(403,'마스터 권한이 필요합니다.')}
async function firebaseUser(idToken,env){idToken=txt(idToken,10000);if(!idToken)fail(400,'Google 로그인 정보가 없습니다.');const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(env.FIREBASE_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken})});const d=await r.json().catch(()=>({}));if(!r.ok){const code=d?.error?.message||'';fail(401,code.includes('EXPIRED')?'Google 로그인이 만료되었습니다. 다시 로그인해 주세요.':'Google 로그인 확인에 실패했습니다.')}const u=d.users?.[0];if(!u||u.disabled)fail(401,'사용할 수 없는 Google 계정입니다.');const gp=(u.providerUserInfo||[]).find(x=>x.providerId==='google.com');if(!gp)fail(403,'Google 계정으로 로그인해야 합니다.');if(u.emailVerified===false)fail(403,'이메일 확인이 완료된 Google 계정이 필요합니다.');return{uid:txt(u.localId,128),email:txt(u.email||gp.email,180).toLowerCase(),name:txt(u.displayName||gp.displayName||(u.email||'').split('@')[0],60)||'마스터 신청자',photo:txt(u.photoUrl||gp.photoUrl,1000)}}
async function idLogin(req,env){const b=await req.json().catch(()=>({})),role=txt(b.role,10);if(!['teacher','student','master'].includes(role))fail(400,'로그인 구분을 확인하세요.');const u=await byLogin(env,b.loginId);if(!u||u.role!==role)fail(401,'ID 또는 비밀번호가 맞지 않습니다.');if(u.active!==1)fail(403,'이용이 중지된 계정입니다.');if(u.locked_until&&u.locked_until>now())fail(429,'로그인 실패가 반복되어 10분간 잠겨 있습니다.');if(!(await verifyPassword(b.password,u.password_hash))){const c=Number(u.failed_count||0)+1,l=c>=5?new Date(Date.now()+LOCK).toISOString():null;await env.DB.prepare('UPDATE core_users SET failed_count=?,locked_until=?,updated_at=? WHERE id=?').bind(c>=5?0:c,l,now(),u.id).run();fail(401,'ID 또는 비밀번호가 맞지 않습니다.')}const n=now();await env.DB.batch([env.DB.prepare('UPDATE core_users SET failed_count=0,locked_until=NULL,last_login_at=?,updated_at=? WHERE id=?').bind(n,n,u.id),env.DB.prepare('DELETE FROM core_sessions WHERE expires_at<=?').bind(n)]);return{token:await newSession(env,u.id),user:{loginId:u.login_id,name:u.name,role:u.role}}}
async function googleMasterLogin(req,env){const b=await req.json().catch(()=>({})),g=await firebaseUser(b.idToken,env);const u=await env.DB.prepare("SELECT u.* FROM core_master_google_accounts g JOIN core_users u ON u.id=g.user_id WHERE g.firebase_uid=? AND u.role='master'").bind(g.uid).first();if(!u){const a=await env.DB.prepare('SELECT status FROM core_master_applications WHERE firebase_uid=?').bind(g.uid).first();if(a?.status==='pending')fail(403,'마스터 승인 대기 중입니다.');if(a?.status==='rejected')fail(403,'마스터 신청이 승인되지 않았습니다. 학원데스크에 문의하세요.');fail(403,'승인된 마스터 계정이 아닙니다. 먼저 마스터 신청을 해주세요.')}if(u.active!==1)fail(403,'이용이 중지된 마스터 계정입니다.');const n=now();await env.DB.prepare('UPDATE core_users SET last_login_at=?,updated_at=? WHERE id=?').bind(n,n,u.id).run();return{token:await newSession(env,u.id),user:{loginId:u.login_id,name:u.name,role:'master'}}}
async function applyMaster(req,env){const b=await req.json().catch(()=>({})),g=await firebaseUser(b.idToken,env),linked=await env.DB.prepare('SELECT user_id FROM core_master_google_accounts WHERE firebase_uid=?').bind(g.uid).first();if(linked)return{ok:true,status:'approved',message:'이미 승인된 마스터 계정입니다.'};const old=await env.DB.prepare('SELECT status FROM core_master_applications WHERE firebase_uid=?').bind(g.uid).first(),n=now();if(old){await env.DB.prepare("UPDATE core_master_applications SET email=?,name=?,photo_url=?,status='pending',requested_at=?,reviewed_at=NULL,reviewed_by=NULL,note=NULL WHERE firebase_uid=?").bind(g.email,g.name,g.photo,n,g.uid).run()}else{await env.DB.prepare("INSERT INTO core_master_applications(firebase_uid,email,name,photo_url,status,requested_at) VALUES(?,?,?,?,'pending',?)").bind(g.uid,g.email,g.name,g.photo,n).run()}return{ok:true,status:'pending',message:'마스터 신청이 접수되었습니다. 기존 마스터 승인 후 로그인할 수 있습니다.'}}
async function listApplications(env,c){requireMaster(c);const r=await env.DB.prepare("SELECT firebase_uid,email,name,photo_url,status,requested_at,reviewed_at FROM core_master_applications WHERE status='pending' ORDER BY requested_at").all();return{applications:r.results}}
async function uniqueMasterLogin(env,uid){const h=(await sha(uid)).slice(0,10).toUpperCase();let id=`GMASTER-${h}`,n=1;while(await byLogin(env,id)){id=`GMASTER-${h}-${n++}`}return id}
async function approveApplication(env,c,uid){requireMaster(c);uid=txt(uid,128);const a=await env.DB.prepare('SELECT * FROM core_master_applications WHERE firebase_uid=?').bind(uid).first();if(!a)fail(404,'마스터 신청을 찾을 수 없습니다.');const linked=await env.DB.prepare('SELECT user_id FROM core_master_google_accounts WHERE firebase_uid=?').bind(uid).first();const n=now();let userId=linked?.user_id;if(!userId){userId=crypto.randomUUID();const loginId=await uniqueMasterLogin(env,uid);await env.DB.batch([env.DB.prepare("INSERT INTO core_users(id,login_id,password_hash,name,role,active,must_change_password,created_at,updated_at) VALUES(?,?,?,?,'master',1,0,?,?)").bind(userId,loginId,'google-only',a.name,n,n),env.DB.prepare('INSERT INTO core_master_google_accounts(firebase_uid,user_id,email,linked_at,linked_by) VALUES(?,?,?,?,?)').bind(uid,userId,a.email,n,c.user.id)])}await env.DB.prepare("UPDATE core_master_applications SET status='approved',reviewed_at=?,reviewed_by=?,note=NULL WHERE firebase_uid=?").bind(n,c.user.id,uid).run();await audit(env,c.user.id,'master.google.approve','user',uid,{email:a.email});return{ok:true}}
async function rejectApplication(req,env,c,uid){requireMaster(c);uid=txt(uid,128);const a=await env.DB.prepare('SELECT * FROM core_master_applications WHERE firebase_uid=?').bind(uid).first();if(!a)fail(404,'마스터 신청을 찾을 수 없습니다.');if(await env.DB.prepare('SELECT user_id FROM core_master_google_accounts WHERE firebase_uid=?').bind(uid).first())fail(409,'이미 승인된 마스터는 신청 거절로 해제할 수 없습니다.');const b=await req.json().catch(()=>({}));await env.DB.prepare("UPDATE core_master_applications SET status='rejected',reviewed_at=?,reviewed_by=?,note=? WHERE firebase_uid=?").bind(now(),c.user.id,txt(b.note,300)||null,uid).run();await audit(env,c.user.id,'master.google.reject','application',uid,{email:a.email});return{ok:true}}
async function route(req,env){const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req,env)});if(req.method==='GET'&&p==='/health')return json(req,env,{ok:true,service:'my247-master-auth'});if(req.method==='POST'&&p==='/api/auth/id-login')return json(req,env,await idLogin(req,env));if(req.method==='POST'&&p==='/api/auth/google-master')return json(req,env,await googleMasterLogin(req,env));if(req.method==='POST'&&p==='/api/master/apply')return json(req,env,await applyMaster(req,env),201);const c=await sessionAuth(req,env);if(req.method==='GET'&&p==='/api/master/applications')return json(req,env,await listApplications(env,c));let m;if(req.method==='POST'&&(m=/^\/api\/master\/applications\/([^/]+)\/approve$/.exec(p)))return json(req,env,await approveApplication(env,c,decodeURIComponent(m[1])));if(req.method==='POST'&&(m=/^\/api\/master\/applications\/([^/]+)\/reject$/.exec(p)))return json(req,env,await rejectApplication(req,env,c,decodeURIComponent(m[1])));fail(404,'요청한 기능을 찾을 수 없습니다.')}
export default{async fetch(req,env){try{return await route(req,env)}catch(e){return json(req,env,{ok:false,message:e.message||'서버 오류'},e.status||500)}}};
