(()=>{
const COUNSEL_STORAGE='etoos247_counseling_preview_v1';
const SCORE_STORAGE='etoos247_mock_scores_preview_v1';
const students=[
{id:'M001',name:'김도윤',campus:'수성1관'},{id:'M002',name:'이서윤',campus:'수성1관'},{id:'M003',name:'박준호',campus:'수성1관'},{id:'M004',name:'최지우',campus:'수성2관'},{id:'M005',name:'정민재',campus:'수성2관'}];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const localStamp=iso=>{const d=new Date(iso);return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)};
const fmt=v=>v==null||Number.isNaN(Number(v))?'-':String(v);
const avg=vals=>{const a=vals.map(Number).filter(Number.isFinite);return a.length?Math.round((a.reduce((x,y)=>x+y,0)/a.length)*10)/10:null};
const inputNum=id=>{const el=$(id);if(!el||el.value==='')return null;const n=Number(el.value);return Number.isFinite(n)?n:null};
function withInquiry(r){return {...r,inquiryPct:avg([r.socialPct,r.sciencePct]),inquiryGrade:avg([r.socialGrade,r.scienceGrade])}}
function readCounsel(){try{return JSON.parse(localStorage.getItem(COUNSEL_STORAGE)||'[]')}catch{return[]}}
function writeCounsel(v){localStorage.setItem(COUNSEL_STORAGE,JSON.stringify(v))}
function readScores(){try{return JSON.parse(localStorage.getItem(SCORE_STORAGE)||'[]')}catch{return[]}}
function writeScores(v){localStorage.setItem(SCORE_STORAGE,JSON.stringify(v))}
function seedCounsel(){if(localStorage.getItem(COUNSEL_STORAGE))return;writeCounsel([{id:'demo-1',studentId:'M001',studentName:'김도윤',subject:'수학',counselor:'교사 자동입력',counselingDate:today(),inputAt:new Date().toISOString(),counseleeType:'학생',counseleeName:'김도윤',content:'주간 학습계획과 수학 오답 정리 방식을 점검했습니다. 다음 상담 때 계획 이행률을 다시 확인합니다.',demo:true},{id:'demo-2',studentId:'M002',studentName:'이서윤',subject:'입시',counselor:'교사 자동입력',counselingDate:today(),inputAt:new Date().toISOString(),counseleeType:'학생',counseleeName:'이서윤',content:'희망 대학과 현재 성적 흐름을 기준으로 학습 우선순위를 임시 정리했습니다.',demo:true}])}
function seedScores(){if(localStorage.getItem(SCORE_STORAGE))return;writeScores([
{id:'score-demo-1',studentId:'M001',studentName:'김도윤',examDate:'2026-03-26',examName:'3월 학력평가 · 예시',korStd:118,korPct:78,korGrade:3,mathStd:122,mathPct:82,mathGrade:3,engGrade:2,socialPct:76,socialGrade:3,sciencePct:71,scienceGrade:4,demo:true},
{id:'score-demo-2',studentId:'M001',studentName:'김도윤',examDate:'2026-06-04',examName:'6월 모의평가 · 예시',korStd:124,korPct:84,korGrade:3,mathStd:128,mathPct:88,mathGrade:2,engGrade:2,socialPct:81,socialGrade:3,sciencePct:77,scienceGrade:3,demo:true},
{id:'score-demo-3',studentId:'M001',studentName:'김도윤',examDate:'2026-07-10',examName:'7월 학력평가 · 예시',korStd:128,korPct:88,korGrade:2,mathStd:132,mathPct:91,mathGrade:2,engGrade:1,socialPct:85,socialGrade:2.5,sciencePct:82,scienceGrade:3,demo:true},
{id:'score-demo-4',studentId:'M002',studentName:'이서윤',examDate:'2026-06-04',examName:'6월 모의평가 · 예시',korStd:130,korPct:90,korGrade:2,mathStd:125,mathPct:85,mathGrade:3,engGrade:2,socialPct:91,socialGrade:2,sciencePct:null,scienceGrade:null,demo:true}
])}
function counselSelected(){return students.find(s=>s.id===$('#counselStudent')?.value)||students[0]}
function scoreSelected(){return students.find(s=>s.id===$('#scoreStudent')?.value)||students[0]}
function renderCounsel(){const s=counselSelected();const rows=readCounsel().filter(x=>x.studentId===s.id).sort((a,b)=>String(b.counselingDate||'').localeCompare(String(a.counselingDate||''))||String(b.inputAt||'').localeCompare(String(a.inputAt||'')));$('#studentLogTitle').textContent=`${s.name} 학생 상담일지`;$('#studentLogCount').textContent=`${rows.length}건`;const box=$('#studentCounselingList');if(!rows.length){box.innerHTML='<div class="counseling-empty">등록된 상담기록이 없습니다.</div>';return}box.innerHTML=rows.map(r=>`<article class="counseling-record"><div class="record-date"><strong>${esc(r.counselingDate)}</strong><span>${esc(r.subject)}</span></div><div class="record-body"><div class="record-meta"><b>${esc(r.counselor)}</b><span>피상담자 ${esc(r.counseleeType)} · ${esc(r.counseleeName||'-')}</span><time>입력 ${esc(localStamp(r.inputAt))}</time>${r.demo?'<em>예시</em>':''}</div><p>${esc(r.content)}</p></div></article>`).join('')}
function syncCounselStudent(){const s=counselSelected();$('#studentLinkKey').textContent=`${s.id} · ${s.name} · ${s.campus}`;if($('#counseleeType').value==='학생')$('#counseleeName').value=s.name;if($('#scoreStudent')&&$('#scoreStudent').value!==s.id)$('#scoreStudent').value=s.id;renderCounsel();renderScores()}
function syncScoreStudent(){const s=scoreSelected();if($('#counselStudent')&&$('#counselStudent').value!==s.id){$('#counselStudent').value=s.id;$('#studentLinkKey').textContent=`${s.id} · ${s.name} · ${s.campus}`;if($('#counseleeType').value==='학생')$('#counseleeName').value=s.name}renderCounsel();renderScores()}
function syncCounselee(){const s=counselSelected();if($('#counseleeType').value==='학생')$('#counseleeName').value=s.name;else if($('#counseleeName').value===s.name)$('#counseleeName').value=''}
function updateInquiryPreview(){const p=avg([inputNum('#socialPct'),inputNum('#sciencePct')]);const g=avg([inputNum('#socialGrade'),inputNum('#scienceGrade')]);$('#inquiryPct').value=p==null?'':p;$('#inquiryGrade').value=g==null?'':g}
function studentScoreRows(){const s=scoreSelected();return readScores().filter(r=>r.studentId===s.id).map(withInquiry).sort((a,b)=>String(a.examDate||'').localeCompare(String(b.examDate||'')))}
function renderScoreSummary(rows,s){const box=$('#scoreSummary');if(!rows.length){box.innerHTML=`<article><small>누계 시험</small><strong>0회</strong><span>${esc(s.name)} 학생</span></article><article><small>최근 탐구평균 백분위</small><strong>-</strong><span>성적 입력 전</span></article><article><small>최근 탐구평균 등급</small><strong>-</strong><span>성적 입력 전</span></article>`;return}const last=rows[rows.length-1];box.innerHTML=`<article><small>누계 시험</small><strong>${rows.length}회</strong><span>${esc(last.examName)}</span></article><article><small>최근 탐구평균 백분위</small><strong>${fmt(last.inquiryPct)}</strong><span>사탐 ${fmt(last.socialPct)} · 과탐 ${fmt(last.sciencePct)}</span></article><article><small>최근 탐구평균 등급</small><strong>${fmt(last.inquiryGrade)}</strong><span>사탐 ${fmt(last.socialGrade)} · 과탐 ${fmt(last.scienceGrade)}</span></article>`}
function renderScoreTable(rows){const wrap=$('#scoreTableWrap');if(!rows.length){wrap.innerHTML='<div class="score-empty">등록된 모의고사 성적이 없습니다.</div>';return}const desc=[...rows].reverse();wrap.innerHTML=`<table class="score-table"><thead><tr><th>시험</th><th>국어 표</th><th>국어 백</th><th>국어 등</th><th>수학 표</th><th>수학 백</th><th>수학 등</th><th>영어 등</th><th>사탐 백</th><th>사탐 등</th><th>과탐 백</th><th>과탐 등</th><th>탐구평균 백</th><th>탐구평균 등</th></tr></thead><tbody>${desc.map(r=>`<tr><td class="exam-cell"><strong>${esc(r.examName)}${r.demo?'<span class="demo-tag">예시</span>':''}</strong><span>${esc(r.examDate)}</span></td><td>${fmt(r.korStd)}</td><td>${fmt(r.korPct)}</td><td>${fmt(r.korGrade)}</td><td>${fmt(r.mathStd)}</td><td>${fmt(r.mathPct)}</td><td>${fmt(r.mathGrade)}</td><td>${fmt(r.engGrade)}</td><td>${fmt(r.socialPct)}</td><td>${fmt(r.socialGrade)}</td><td>${fmt(r.sciencePct)}</td><td>${fmt(r.scienceGrade)}</td><td class="avg-cell">${fmt(r.inquiryPct)}</td><td class="avg-cell">${fmt(r.inquiryGrade)}</td></tr>`).join('')}</tbody></table>`}
function drawScoreChart(rows){const svg=$('#scoreChart');const metric=$('#scoreGraphMetric').value;const W=900,H=350,L=58,R=24,T=28,B=62,PW=W-L-R,PH=H-T-B;const series=metric==='percentile'?[{key:'korPct',label:'국어',cls:'korean'},{key:'mathPct',label:'수학',cls:'math'},{key:'socialPct',label:'사탐',cls:'social'},{key:'sciencePct',label:'과탐',cls:'science'},{key:'inquiryPct',label:'탐구평균',cls:'inquiryavg'}]:[{key:'korGrade',label:'국어',cls:'korean'},{key:'mathGrade',label:'수학',cls:'math'},{key:'engGrade',label:'영어',cls:'english'},{key:'socialGrade',label:'사탐',cls:'social'},{key:'scienceGrade',label:'과탐',cls:'science'},{key:'inquiryGrade',label:'탐구평균',cls:'inquiryavg'}];const yTicks=metric==='percentile'?[100,75,50,25,0]:[1,3,5,7,9];const y=v=>metric==='percentile'?T+(100-v)/100*PH:T+(v-1)/8*PH;const x=i=>rows.length<=1?L+PW/2:L+i*(PW/(rows.length-1));let html='';yTicks.forEach(v=>{const yy=y(v);html+=`<line class="chart-grid" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"></line><text class="chart-axis-label" x="${L-12}" y="${yy+4}" text-anchor="end">${v}</text>`});if(!rows.length){html+=`<text x="450" y="175" text-anchor="middle" class="chart-axis-label">등록된 성적이 없습니다.</text>`;svg.innerHTML=html;$('#scoreLegend').innerHTML='';return}rows.forEach((r,i)=>{const xx=x(i);const label=(r.examDate||'').slice(5).replace('-','.');html+=`<text class="chart-x-label" x="${xx}" y="${H-26}" text-anchor="middle">${esc(label)}</text>`});series.forEach(s=>{const pts=rows.map((r,i)=>({x:x(i),y:y(Number(r[s.key])),v:r[s.key]})).filter(p=>p.v!=null&&Number.isFinite(Number(p.v)));if(!pts.length)return;const d=pts.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' ');html+=`<path d="${d}" class="chart-line series-${s.cls}"></path>`;pts.forEach(p=>{html+=`<circle cx="${p.x}" cy="${p.y}" r="4.5" class="chart-point series-${s.cls}"><title>${esc(s.label)} ${fmt(p.v)}</title></circle>`})});svg.innerHTML=html;$('#scoreLegend').innerHTML=series.map(s=>`<span class="${s.cls}"><i></i>${s.label}</span>`).join('')}
function renderScores(){if(!$('#scoreStudent'))return;const s=scoreSelected();const rows=studentScoreRows();$('#scoreGraphTitle').textContent=`${s.name} 학생 모의고사 추이`;$('#scoreTableTitle').textContent=`${s.name} 학생 모의고사 성적 누계`;$('#scoreCount').textContent=`${rows.length}회`;renderScoreSummary(rows,s);renderScoreTable(rows);drawScoreChart(rows)}
function clearScoreInputs(){['#korStd','#korPct','#korGrade','#mathStd','#mathPct','#mathGrade','#engGrade','#socialPct','#socialGrade','#sciencePct','#scienceGrade'].forEach(id=>{if($(id))$(id).value=''});$('#examName').value='';updateInquiryPreview()}
seedCounsel();seedScores();
const options=students.map(s=>`<option value="${s.id}">${s.id} · ${s.name} · ${s.campus}</option>`).join('');
$('#counselStudent').innerHTML=options;$('#scoreStudent').innerHTML=options;
$('#counselDate').value=today();$('#counselInputDate').value=localStamp(new Date().toISOString());$('#examDate').value=today();
$('#counselStudent').addEventListener('change',syncCounselStudent);$('#scoreStudent').addEventListener('change',syncScoreStudent);$('#counseleeType').addEventListener('change',syncCounselee);$('#scoreGraphMetric').addEventListener('change',renderScores);
['#socialPct','#sciencePct','#socialGrade','#scienceGrade'].forEach(id=>$(id).addEventListener('input',updateInquiryPreview));
$('#counselingForm').addEventListener('submit',e=>{e.preventDefault();const s=counselSelected(),inputAt=new Date().toISOString(),record={id:'preview-'+Date.now(),studentId:s.id,studentName:s.name,subject:$('#counselSubject').value,counselor:'교사 자동입력',counselingDate:$('#counselDate').value,inputAt,counseleeType:$('#counseleeType').value,counseleeName:$('#counseleeName').value.trim(),content:$('#counselBody').value.trim(),demo:false};if(!record.counselingDate||!record.content)return;const all=readCounsel();all.push(record);writeCounsel(all);$('#counselInputDate').value=localStamp(inputAt);$('#counselBody').value='';renderCounsel();const btn=$('#counselingForm button[type="submit"]');const old=btn.textContent;btn.textContent='저장됨 ✓';setTimeout(()=>btn.textContent=old,1300)});
$('#scoreForm').addEventListener('submit',e=>{e.preventDefault();const s=scoreSelected();const base={id:'score-'+Date.now(),studentId:s.id,studentName:s.name,examDate:$('#examDate').value,examName:$('#examName').value.trim(),korStd:inputNum('#korStd'),korPct:inputNum('#korPct'),korGrade:inputNum('#korGrade'),mathStd:inputNum('#mathStd'),mathPct:inputNum('#mathPct'),mathGrade:inputNum('#mathGrade'),engGrade:inputNum('#engGrade'),socialPct:inputNum('#socialPct'),socialGrade:inputNum('#socialGrade'),sciencePct:inputNum('#sciencePct'),scienceGrade:inputNum('#scienceGrade'),demo:false};if(!base.examDate||!base.examName)return;const record=withInquiry(base);const all=readScores();all.push(record);writeScores(all);renderScores();clearScoreInputs();const btn=$('#scoreForm button[type="submit"]');const old=btn.textContent;btn.textContent='성적 저장됨 ✓';setTimeout(()=>btn.textContent=old,1300)});
updateInquiryPreview();syncCounselStudent();
})();