import app from './index.js';
const enc=new TextEncoder(),ITER=600000;
const TABLES=["teacher_campuses","student_applications","teacher_requests","questions","messages","attachments","audit_logs","users","accounts"];
function rewrite(sql){let s=sql;for(const t of TABLES)s=s.replace(new RegExp(`\\b${t}\\b`,"g"),`v2_${t}`);return s}
function dbProxy(db){return {prepare(sql){return db.prepare(rewrite(sql))},batch(stmts){return db.batch(stmts)},exec(sql){return db.exec(rewrite(sql))}}}
function envV2(env){return {...env,DB:dbProxy(env.DB)}}
function cors(request,env){const o=request.headers.get("origin"),a=env.ALLOWED_ORIGIN||"https://etoos247test.github.io";return {"Access-Control-Allow-Origin":o===a?o:a,"Access-Control-Allow-Headers":"Authorization, Content-Type, X-Bootstrap-Secret","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"}}
function json(request,env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(request,env),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function fail(status,message){const e=new Error(message);e.status=status;throw e}
function hex(bytes){return [...bytes].map(x=>x.toString(16).padStart(2,"0")).join("")}
function unhex(s){const a=new Uint8Array(s.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}
async function derive(pw,salt,it=ITER){const k=await crypto.subtle.importKey("raw",enc.encode(pw),"PBKDF2",false,["deriveBits"]);return new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations:it},k,256))}
async function hashPassword(pw){if(String(pw).length<10)fail(400,"비밀번호는 10자 이상이어야 합니다.");const salt=new Uint8Array(16);crypto.getRandomValues(salt);return `pbkdf2-sha256$${ITER}$${hex(salt)}$${hex(await derive(String(pw),salt))}`}
async function verifyPassword(pw,stored){const p=String(stored||"").split("$");if(p.length!==4||p[0]!=="pbkdf2-sha256")return false;const a=await derive(String(pw),unhex(p[2]),Number(p[1])),b=unhex(p[3]);if(a.length!==b.length)return false;if(typeof crypto.subtle.timingSafeEqual==="function")return crypto.subtle.timingSafeEqual(a,b);let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}
function b64url(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function sign(env,payload){if(!env.SESSION_SECRET)fail(500,"SESSION_SECRET 설정이 필요합니다.");const body=b64url(enc.encode(JSON.stringify(payload))),key=await crypto.subtle.importKey("raw",enc.encode(env.SESSION_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign"]),sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(body)));return `${body}.${b64url(sig)}`}
function norm(v){return String(v||"").trim().toUpperCase().slice(0,64)}
function now(){return new Date().toISOString()}
async function tokenFor(env,user,account){const t=Math.floor(Date.now()/1000);return sign(env,{uid:user.uid,name:user.name,email:user.email||`${account.login_id}@etoos247.local`,v:Number(account.token_version),iat:t,exp:t+12*3600})}
async function authRaw(request,env){const h=request.headers.get("authorization")||"",m=/^Bearer\s+(.+)$/i.exec(h);if(!m)fail(401,"로그인이 필요합니다.");const venv=envV2(env);const {verifyFirebaseIdToken}=await import('./firebase-auth.js');const id=await verifyFirebaseIdToken(request,venv);const u=await env.DB.prepare("SELECT * FROM v2_users WHERE uid=?").bind(id.uid).first();if(!u||u.active!==1)fail(403,"현재 이용이 중지된 계정입니다.");return u}
async function login(request,env){const b=await request.json().catch(()=>({})),id=norm(b.loginId),pw=String(b.password||"");const row=await env.DB.prepare("SELECT a.*,u.name,u.email,u.role,u.active,u.campus,u.student_id FROM v2_accounts a JOIN v2_users u ON u.uid=a.uid WHERE a.login_id=?").bind(id).first();if(!row)fail(401,"ID 또는 비밀번호가 맞지 않습니다.");if(row.active!==1||row.account_status!=="active")fail(403,"현재 이용이 중지된 계정입니다.");if(row.locked_until&&row.locked_until>now())fail(429,"로그인 실패가 반복되어 잠시 잠겼습니다.");if(!(await verifyPassword(pw,row.password_hash))){const n=Number(row.failed_count||0)+1,lock=n>=5?new Date(Date.now()+10*60000).toISOString():null;await env.DB.prepare("UPDATE v2_accounts SET failed_count=?,locked_until=?,updated_at=? WHERE uid=?").bind(n>=5?0:n,lock,now(),row.uid).run();fail(401,"ID 또는 비밀번호가 맞지 않습니다.")}await env.DB.prepare("UPDATE v2_accounts SET failed_count=0,locked_until=NULL,last_login_at=?,updated_at=? WHERE uid=?").bind(now(),now(),row.uid).run();const token=await tokenFor(env,row,row);return {sessionToken:token,mustChangePassword:row.must_change_password===1,identity:{uid:row.uid,email:row.email||`${id}@etoos247.local`,name:row.name},profile:{uid:row.uid,name:row.name,role:row.role,active:row.active,campus:row.campus,student_id:row.student_id}}}
async function bootstrap(request,env){if(!env.BOOTSTRAP_SECRET||request.headers.get("x-bootstrap-secret")!==env.BOOTSTRAP_SECRET)fail(403,"초기 관리자 생성 권한이 없습니다.");const c=await env.DB.prepare("SELECT COUNT(*) c FROM v2_users WHERE role='master'").first();if(Number(c?.c||0)>0)fail(409,"마스터가 이미 존재합니다.");const b=await request.json(),id=norm(b.loginId),name=String(b.name||"").trim();if(!/^[A-Z0-9._-]{3,64}$/.test(id)||name.length<2)fail(400,"ID 또는 이름을 확인하세요.");const uid=crypto.randomUUID(),time=now(),ph=await hashPassword(b.password);await env.DB.batch([env.DB.prepare("INSERT INTO v2_users(uid,email,name,role,active,campus,student_id,can_answer_questions,can_approve_students,can_manage_student_info,created_at,updated_at) VALUES(?,?,?,'master',1,NULL,NULL,1,1,1,?,?)").bind(uid,`${id}@etoos247.local`,name,time,time),env.DB.prepare("INSERT INTO v2_accounts(uid,login_id,password_hash,must_change_password,failed_count,account_status,token_version,created_at,updated_at) VALUES(?,?,?,0,0,'active',1,?,?)").bind(uid,id,ph,time,time)]);return {uid,loginId:id,name}}
async function listAccounts(request,env){const u=await authRaw(request,env);if(u.role!=="master")fail(403,"마스터 권한이 필요합니다.");const r=await env.DB.prepare("SELECT u.uid,u.name,u.role,u.active,u.campus,u.student_id,a.login_id,a.must_change_password,a.last_login_at,a.account_status FROM v2_users u JOIN v2_accounts a ON a.uid=u.uid ORDER BY CASE u.role WHEN 'master' THEN 0 WHEN 'teacher' THEN 1 ELSE 2 END,u.name").all();return {accounts:r.results}}
async function createAccount(request,env){const master=await authRaw(request,env);if(master.role!=="master")fail(403,"마스터 권한이 필요합니다.");const b=await request.json(),id=norm(b.loginId),name=String(b.name||"").trim(),role=String(b.role||"");if(!/^[A-Z0-9._-]{3,64}$/.test(id)||name.length<2||!["student","teacher","master"].includes(role))fail(400,"계정 정보를 확인하세요.");let campus=null,studentId=null;if(role==="student"){campus=b.campus;if(!["suseong1","suseong2"].includes(campus))fail(400,"소속관을 선택하세요.");studentId=norm(b.studentId||id);const prefix=campus==="suseong1"?"M":"S";if(!new RegExp(`^${prefix}\\d{3}$`).test(studentId))fail(400,"학생번호는 M001 또는 S001 형식이어야 합니다.")}const uid=crypto.randomUUID(),time=now(),ph=await hashPassword(b.temporaryPassword);const ans=role==="master"?1:role==="teacher"&&b.canAnswerQuestions?1:0,appv=role==="master"?1:role==="teacher"&&b.canApproveStudents?1:0,mng=role==="master"?1:role==="teacher"&&b.canManageStudentInfo?1:0;const stm=[env.DB.prepare("INSERT INTO v2_users(uid,email,name,role,active,campus,student_id,can_answer_questions,can_approve_students,can_manage_student_info,created_at,updated_at) VALUES(?,?,?,?,1,?,?,?,?,?,?,?)").bind(uid,`${id}@etoos247.local`,name,role,campus,studentId,ans,appv,mng,time,time),env.DB.prepare("INSERT INTO v2_accounts(uid,login_id,password_hash,must_change_password,failed_count,account_status,token_version,created_at,updated_at) VALUES(?,?,?,1,0,'active',1,?,?)").bind(uid,id,ph,time,time)];if(role==="teacher"){for(const c of (b.campuses||[]).filter(x=>["suseong1","suseong2"].includes(x)))stm.push(env.DB.prepare("INSERT INTO v2_teacher_campuses(teacher_uid,campus,created_at) VALUES(?,?,?)").bind(uid,c,time))}await env.DB.batch(stm);return {uid,loginId:id,name,role,studentId}}
async function resetPassword(request,env,uid){const m=await authRaw(request,env);if(m.role!=="master")fail(403,"마스터 권한이 필요합니다.");const b=await request.json(),ph=await hashPassword(b.temporaryPassword);await env.DB.prepare("UPDATE v2_accounts SET password_hash=?,must_change_password=1,token_version=token_version+1,failed_count=0,locked_until=NULL,updated_at=? WHERE uid=?").bind(ph,now(),uid).run();return {ok:true}}
async function setActive(request,env,uid){const m=await authRaw(request,env);if(m.role!=="master")fail(403,"마스터 권한이 필요합니다.");const b=await request.json(),a=b.active?1:0;if(uid===m.uid&&!a)fail(400,"현재 관리자 계정은 중지할 수 없습니다.");await env.DB.batch([env.DB.prepare("UPDATE v2_users SET active=?,updated_at=? WHERE uid=?").bind(a,now(),uid),env.DB.prepare("UPDATE v2_accounts SET account_status=?,token_version=token_version+1,updated_at=? WHERE uid=?").bind(a?"active":"disabled",now(),uid)]);return {ok:true,active:a}}
async function logout(request,env){const u=await authRaw(request,env);await env.DB.prepare("UPDATE v2_accounts SET token_version=token_version+1,updated_at=? WHERE uid=?").bind(now(),u.uid).run();return {ok:true}}
async function changePassword(request,env){const u=await authRaw(request,env),b=await request.json(),a=await env.DB.prepare("SELECT * FROM v2_accounts WHERE uid=?").bind(u.uid).first();if(!(await verifyPassword(b.currentPassword,a.password_hash)))fail(401,"현재 비밀번호가 맞지 않습니다.");const ph=await hashPassword(b.newPassword);await env.DB.prepare("UPDATE v2_accounts SET password_hash=?,must_change_password=0,token_version=token_version+1,updated_at=? WHERE uid=?").bind(ph,now(),u.uid).run();const fresh=await env.DB.prepare("SELECT * FROM v2_accounts WHERE uid=?").bind(u.uid).first();return {ok:true,sessionToken:await tokenFor(env,u,fresh)}}
async function route(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors(request,env)});if(url.pathname==="/health")return json(request,env,{ok:true,service:"etoos247-qa-v2",firebase:false,auth:"company-id"});if(url.pathname==="/api/v2/login"&&request.method==="POST")return json(request,env,await login(request,env));if(url.pathname==="/api/v2/bootstrap-master"&&request.method==="POST")return json(request,env,await bootstrap(request,env),201);if(url.pathname==="/api/v2/accounts"&&request.method==="GET")return json(request,env,await listAccounts(request,env));if(url.pathname==="/api/v2/accounts"&&request.method==="POST")return json(request,env,await createAccount(request,env),201);if(url.pathname==="/api/v2/logout"&&request.method==="POST")return json(request,env,await logout(request,env));if(url.pathname==="/api/v2/change-password"&&request.method==="POST")return json(request,env,await changePassword(request,env));let m=/^\/api\/v2\/accounts\/([^/]+)\/reset-password$/.exec(url.pathname);if(m&&request.method==="POST")return json(request,env,await resetPassword(request,env,m[1]));m=/^\/api\/v2\/accounts\/([^/]+)\/active$/.exec(url.pathname);if(m&&request.method==="POST")return json(request,env,await setActive(request,env,m[1]));return app.fetch(request,envV2(env))}
export default{async fetch(request,env){try{return await route(request,env)}catch(e){console.error(e);return json(request,env,{message:e.status?e.message:"서버 처리 중 오류가 발생했습니다."},Number(e.status)||500)}}};
